// Sub-areas / localities for each city
// URL: /escorts-service/:city/:area

const AREAS = {
  // ─── DELHI ────────────────────────────────────────────────────────────────
  'delhi': [
    { name: 'Connaught Place',     slug: 'connaught-place' },
    { name: 'Karol Bagh',          slug: 'karol-bagh' },
    { name: 'Lajpat Nagar',        slug: 'lajpat-nagar' },
    { name: 'Dwarka',              slug: 'dwarka' },
    { name: 'South Delhi',         slug: 'south-delhi' },
    { name: 'Rohini',              slug: 'rohini' },
    { name: 'Saket',               slug: 'saket' },
    { name: 'Janakpuri',           slug: 'janakpuri' },
    { name: 'Vasant Kunj',         slug: 'vasant-kunj' },
    { name: 'Mahipalpur',          slug: 'mahipalpur' },
    { name: 'New Friends Colony',  slug: 'new-friends-colony' },
    { name: 'Kirti Nagar',         slug: 'kirti-nagar' },
    { name: 'East of Kailash',     slug: 'east-of-kailash' },
    { name: 'Shalimar Bagh',       slug: 'shalimar-bagh' },
    { name: 'Rajouri Garden',      slug: 'rajouri-garden' },
    { name: 'Mayur Vihar Phase 1', slug: 'mayur-vihar-phase-1' },
    { name: 'Mayur Vihar',         slug: 'mayur-vihar' },
    { name: 'Uttam Nagar',         slug: 'uttam-nagar' },
    { name: 'Dilshad Garden',      slug: 'dilshad-garden' },
    { name: 'Jangpura',            slug: 'jangpura' },
    { name: 'Green Park',          slug: 'green-park' },
    { name: 'Mukherjee Nagar',     slug: 'mukherjee-nagar' },
    { name: 'Nehru Place',         slug: 'nehru-place' },
    { name: 'Patparganj',          slug: 'patparganj' },
    { name: 'Paharganj',           slug: 'paharganj' },
    { name: 'Daryaganj',           slug: 'daryaganj' },
    { name: 'Kalkaji',             slug: 'kalkaji' },
    { name: 'Paschim Vihar',       slug: 'paschim-vihar' },
    { name: 'Delhi Civil Lines',   slug: 'delhi-civil-lines' },
    { name: 'Patel Nagar',         slug: 'patel-nagar' },
    { name: 'Model Town',          slug: 'model-town' },
    { name: 'Okhla Phase 2',       slug: 'okhla-phase-2' },
    { name: 'Netaji Subhash Place', slug: 'netaji-subhash-place' },
    { name: 'Gulmohar Park',       slug: 'gulmohar-park' },
    { name: 'Sarvodaya Enclave',   slug: 'sarvodaya-enclave' },
    { name: 'Khanpur',             slug: 'khanpur' },
    { name: 'Nariana Vihar',       slug: 'nariana-vihar' },
    { name: 'Krishna Nagar',       slug: 'krishna-nagar' },
  ],

  // ─── MUMBAI ───────────────────────────────────────────────────────────────
  'mumbai': [
    { name: 'Bandra',              slug: 'bandra' },
    { name: 'Juhu',                slug: 'juhu' },
    { name: 'Andheri',             slug: 'andheri' },
    { name: 'Colaba',              slug: 'colaba' },
    { name: 'Powai',               slug: 'powai' },
    { name: 'Borivali',            slug: 'borivali' },
    { name: 'Kurla',               slug: 'kurla' },
    { name: 'Dadar',               slug: 'dadar' },
    { name: 'Malad',               slug: 'malad' },
    { name: 'Goregaon',            slug: 'goregaon' },
    { name: 'Kandivali',           slug: 'kandivali' },
    { name: 'Jogeshwari',          slug: 'jogeshwari' },
    { name: 'Santacruz',           slug: 'santacruz' },
    { name: 'Vile Parle',          slug: 'vile-parle' },
    { name: 'Khar',                slug: 'khar' },
    { name: 'Versova',             slug: 'versova' },
    { name: 'Charni Road',         slug: 'charni-road' },
    { name: 'Lower Parel',         slug: 'lower-parel' },
    { name: 'Worli',               slug: 'worli' },
    { name: 'Chembur',             slug: 'chembur' },
    { name: 'Mulund',              slug: 'mulund' },
    { name: 'Ghatkopar',           slug: 'ghatkopar' },
    { name: 'Wadala',              slug: 'wadala' },
    { name: 'Byculla',             slug: 'byculla' },
    { name: 'Fort',                slug: 'fort' },
    { name: 'Prabhadevi',          slug: 'prabhadevi' },
    { name: 'Sakinaka',            slug: 'sakinaka' },
    { name: 'Kanjurmarg',          slug: 'kanjurmarg' },
    { name: 'Masjid Bandar',       slug: 'masjid-bandar' },
    { name: 'Mumbai Airport',      slug: 'mumbai-airport' },
    { name: 'Lalbagh Mumbai',      slug: 'lalbagh-mumbai' },
    { name: 'CST',                 slug: 'cst' },
    { name: 'Govandi',             slug: 'govandi' },
    { name: 'Dombivli',            slug: 'dombivli' },
    { name: 'Mumbra',              slug: 'mumbra' },
    { name: 'Naigaon',             slug: 'naigaon' },
    { name: 'Virar',               slug: 'virar' },
    { name: 'Vasai',               slug: 'vasai' },
    { name: 'Thane West',          slug: 'thane-west' },
    { name: 'Ghodbunder Road',     slug: 'ghodbunder-road' },
  ],

  // ─── BANGALORE ────────────────────────────────────────────────────────────
  'bangalore': [
    { name: 'Koramangala',         slug: 'koramangala' },
    { name: 'Indiranagar',         slug: 'indiranagar' },
    { name: 'MG Road',             slug: 'mg-road' },
    { name: 'Whitefield',          slug: 'whitefield' },
    { name: 'Electronic City',     slug: 'electronic-city' },
    { name: 'HSR Layout',          slug: 'hsr-layout' },
    { name: 'Marathahalli',        slug: 'marathahalli' },
    { name: 'Jayanagar',           slug: 'jayanagar' },
    { name: 'JP Nagar',            slug: 'jp-nagar' },
    { name: 'Bannerghatta Road',   slug: 'bannerghatta-road' },
    { name: 'Bellandur',           slug: 'bellandur' },
    { name: 'Sarjapur Road',       slug: 'sarjapur-road' },
    { name: 'BTM Layout',          slug: 'btm-layout' },
    { name: 'Rajajinagar',         slug: 'rajajinagar' },
    { name: 'Malleshwaram',        slug: 'malleshwaram' },
    { name: 'Yelahanka',           slug: 'yelahanka' },
    { name: 'Hebbal',              slug: 'hebbal' },
    { name: 'KR Puram',            slug: 'kr-puram' },
    { name: 'Madivala',            slug: 'madivala' },
    { name: 'Hongasandra',         slug: 'hongasandra' },
    { name: 'Kammanahalli',        slug: 'kammanahalli' },
    { name: 'Cooke Town',          slug: 'cooke-town' },
    { name: 'ITPL',                slug: 'itpl' },
    { name: 'Kanakapura Road',     slug: 'kanakapura-road' },
    { name: 'UB City',             slug: 'ub-city' },
    { name: 'Garuda Mall',         slug: 'garuda-mall' },
    { name: 'Vidhan Soudha',       slug: 'vidhan-soudha' },
  ],

  // ─── HYDERABAD ────────────────────────────────────────────────────────────
  'hyderabad': [
    { name: 'Hitech City',         slug: 'hitech-city' },
    { name: 'Banjara Hills',       slug: 'banjara-hills' },
    { name: 'Jubilee Hills',       slug: 'jubilee-hills' },
    { name: 'Gachibowli',          slug: 'gachibowli' },
    { name: 'Secunderabad',        slug: 'secunderabad' },
    { name: 'Kukatpally',          slug: 'kukatpally' },
    { name: 'Madhapur',            slug: 'madhapur' },
    { name: 'Begumpet',            slug: 'begumpet' },
    { name: 'Ameerpet',            slug: 'ameerpet' },
    { name: 'Somajiguda',          slug: 'somajiguda' },
    { name: 'Kondapur',            slug: 'kondapur' },
    { name: 'Manikonda',           slug: 'manikonda' },
    { name: 'LB Nagar',            slug: 'lb-nagar' },
    { name: 'Dilsukhnagar',        slug: 'dilsukhnagar' },
    { name: 'Uppal',               slug: 'uppal' },
    { name: 'Attapur',             slug: 'attapur' },
    { name: 'Mehdipatnam',         slug: 'mehdipatnam' },
    { name: 'Charminar',           slug: 'charminar' },
    { name: 'Tolichowki',          slug: 'tolichowki' },
    { name: 'Sainikpuri',          slug: 'sainikpuri' },
    { name: 'AS Rao Nagar',        slug: 'as-rao-nagar' },
  ],

  // ─── CHENNAI ──────────────────────────────────────────────────────────────
  'chennai': [
    { name: 'Anna Nagar',          slug: 'anna-nagar' },
    { name: 'T. Nagar',            slug: 't-nagar' },
    { name: 'Velachery',           slug: 'velachery' },
    { name: 'Adyar',               slug: 'adyar' },
    { name: 'Nungambakkam',        slug: 'nungambakkam' },
    { name: 'OMR',                 slug: 'omr' },
    { name: 'Porur',               slug: 'porur' },
    { name: 'Perambur',            slug: 'perambur' },
    { name: 'Ambattur',            slug: 'ambattur' },
    { name: 'Vadapalani',          slug: 'vadapalani' },
    { name: 'Kodambakkam',         slug: 'kodambakkam' },
    { name: 'Mylapore',            slug: 'mylapore' },
    { name: 'Besant Nagar',        slug: 'besant-nagar' },
    { name: 'Egmore',              slug: 'egmore' },
    { name: 'Royapettah',          slug: 'royapettah' },
    { name: 'Kilpauk',             slug: 'kilpauk' },
    { name: 'Guindy',              slug: 'guindy' },
    { name: 'Tambaram',            slug: 'tambaram' },
    { name: 'Chromepet',           slug: 'chromepet' },
    { name: 'Sholinganallur',      slug: 'sholinganallur' },
  ],

  // ─── KOLKATA ──────────────────────────────────────────────────────────────
  'kolkata': [
    { name: 'Park Street',         slug: 'park-street' },
    { name: 'Salt Lake',           slug: 'salt-lake' },
    { name: 'New Town',            slug: 'new-town' },
    { name: 'Esplanade',           slug: 'esplanade' },
    { name: 'Howrah',              slug: 'howrah' },
    { name: 'Ballygunge',          slug: 'ballygunge' },
    { name: 'Jadavpur',            slug: 'jadavpur' },
    { name: 'Tollygunge',          slug: 'tollygunge' },
    { name: 'Behala',              slug: 'behala' },
    { name: 'Dum Dum',             slug: 'dum-dum' },
    { name: 'Barasat',             slug: 'barasat' },
    { name: 'Alipore',             slug: 'alipore' },
    { name: 'Gariahat',            slug: 'gariahat' },
    { name: 'Shyambazar',          slug: 'shyambazar' },
    { name: 'Sealdah',             slug: 'sealdah' },
    { name: 'Belgharia',           slug: 'belgharia' },
    { name: 'Rajarhat',            slug: 'rajarhat' },
    { name: 'Krishnanagar',        slug: 'krishnanagar' },
  ],

  // ─── PUNE ─────────────────────────────────────────────────────────────────
  'pune': [
    { name: 'Koregaon Park',       slug: 'koregaon-park' },
    { name: 'Kalyani Nagar',       slug: 'kalyani-nagar' },
    { name: 'Viman Nagar',         slug: 'viman-nagar' },
    { name: 'Hadapsar',            slug: 'hadapsar' },
    { name: 'Kothrud',             slug: 'kothrud' },
    { name: 'Shivajinagar',        slug: 'shivajinagar' },
    { name: 'Baner',               slug: 'baner' },
    { name: 'Pashan',              slug: 'pashan' },
    { name: 'Kondhwa',             slug: 'kondhwa' },
    { name: 'Katraj',              slug: 'katraj' },
    { name: 'Dattawadi',           slug: 'dattawadi' },
    { name: 'Yerwada',             slug: 'yerwada' },
    { name: 'Pimple Saudagar',     slug: 'pimple-saudagar' },
    { name: 'Pimple Gurav',        slug: 'pimple-gurav' },
    { name: 'Dehu Road',           slug: 'dehu-road' },
    { name: 'Khadki',              slug: 'khadki' },
    { name: 'Bibwewadi',           slug: 'bibwewadi' },
    { name: 'Magarpatta',          slug: 'magarpatta' },
    { name: 'Ravet',               slug: 'ravet' },
    { name: 'Boat Club Road',      slug: 'boat-club-road' },
    { name: 'Ghorpadi',            slug: 'ghorpadi' },
    { name: 'Dighi',               slug: 'dighi' },
    { name: 'Raviwar Peth',        slug: 'raviwar-peth' },
    { name: 'Shaniwar Wada',       slug: 'shaniwar-wada' },
    { name: 'Pathardi Phata',      slug: 'pathardi-phata' },
    { name: 'Phursungi',           slug: 'phursungi' },
    { name: 'Lonapur',             slug: 'lonapur' },
  ],

  // ─── AHMEDABAD ────────────────────────────────────────────────────────────
  'ahmedabad': [
    { name: 'CG Road',             slug: 'cg-road' },
    { name: 'Navrangpura',         slug: 'navrangpura' },
    { name: 'Satellite',           slug: 'satellite' },
    { name: 'SG Highway',          slug: 'sg-highway' },
    { name: 'Vastrapur',           slug: 'vastrapur' },
    { name: 'Paldi',               slug: 'paldi' },
    { name: 'Memnagar',            slug: 'memnagar' },
    { name: 'CTM',                 slug: 'ctm' },
    { name: 'Naroda GIDC',         slug: 'naroda-gidc' },
    { name: 'Odhav',               slug: 'odhav' },
    { name: 'Odhav GIDC',          slug: 'odhav-gidc' },
    { name: 'Odhav Road',          slug: 'odhav-road' },
    { name: 'Gota',                slug: 'gota' },
    { name: 'Nikol',               slug: 'nikol' },
    { name: 'Rakhial',             slug: 'rakhial' },
    { name: 'Saraspur',            slug: 'saraspur' },
    { name: 'Gomtipur',            slug: 'gomtipur' },
    { name: 'Amroli',              slug: 'amroli' },
    { name: 'Ratan Pole',          slug: 'ratan-pole' },
    { name: 'Manek Chowk',         slug: 'manek-chowk' },
    { name: 'Usmanpura',           slug: 'usmanpura' },
    { name: 'Shahibagh',           slug: 'shahibagh' },
    { name: 'Gandhi Road',         slug: 'gandhi-road' },
    { name: 'Juna Wadaj',          slug: 'juna-wadaj' },
    { name: 'Sola',                slug: 'sola' },
    { name: 'Sola Road',           slug: 'sola-road' },
    { name: 'Vasna',               slug: 'vasna' },
    { name: 'Vasna Road',          slug: 'vasna-road' },
    { name: 'Isanpur',             slug: 'isanpur' },
    { name: 'Naranpura',           slug: 'naranpura' },
    { name: 'Bopal',               slug: 'bopal' },
    { name: 'South Bopal',         slug: 'south-bopal' },
    { name: 'Sarkhej',             slug: 'sarkhej' },
    { name: 'Girdhar Nagar',       slug: 'girdhar-nagar' },
    { name: 'Madhupura',           slug: 'madhupura' },
    { name: 'Khokhara',            slug: 'khokhara' },
  ],

  // ─── NOIDA ────────────────────────────────────────────────────────────────
  'noida': [
    { name: 'Sector 18',           slug: 'sector-18' },
    { name: 'Sector 62',           slug: 'sector-62' },
    { name: 'Sector 50',           slug: 'sector-50' },
    { name: 'Sector 12',           slug: 'sector-12' },
    { name: 'Sector 16',           slug: 'sector-16' },
    { name: 'Sector 17',           slug: 'sector-17' },
    { name: 'Sector 22',           slug: 'sector-22' },
    { name: 'Sector 25',           slug: 'sector-25' },
    { name: 'Sector 27',           slug: 'sector-27' },
    { name: 'Sector 45',           slug: 'sector-45' },
    { name: 'Sector 47',           slug: 'sector-47' },
    { name: 'Sector 49',           slug: 'sector-49' },
    { name: 'Sector 53',           slug: 'sector-53' },
    { name: 'Sector 56',           slug: 'sector-56' },
    { name: 'Sector 63',           slug: 'sector-63' },
    { name: 'Sector 81',           slug: 'sector-81' },
    { name: 'Sector 86',           slug: 'sector-86' },
    { name: 'Sector 89',           slug: 'sector-89' },
    { name: 'Sector 90',           slug: 'sector-90' },
    { name: 'Sector 94',           slug: 'sector-94' },
    { name: 'Sector 97',           slug: 'sector-97' },
    { name: 'Sector 98',           slug: 'sector-98' },
    { name: 'Sector 100',          slug: 'sector-100' },
    { name: 'Sector 101',          slug: 'sector-101' },
    { name: 'Sector 115',          slug: 'sector-115' },
    { name: 'Sector 121',          slug: 'sector-121' },
    { name: 'Sector 129',          slug: 'sector-129' },
    { name: 'Sector 132',          slug: 'sector-132' },
    { name: 'Sector 137',          slug: 'sector-137' },
    { name: 'Sector 138',          slug: 'sector-138' },
    { name: 'Sector 146',          slug: 'sector-146' },
    { name: 'Sector 166',          slug: 'sector-166' },
    { name: 'Greater Noida',       slug: 'greater-noida' },
    { name: 'Yamuna Expressway',   slug: 'yamuna-expressway' },
  ],

  // ─── GURUGRAM ─────────────────────────────────────────────────────────────
  'gurugram': [
    { name: 'DLF Phase 1',         slug: 'dlf-phase-1' },
    { name: 'DLF Phase 4',         slug: 'dlf-phase-4' },
    { name: 'Golf Course Road',    slug: 'golf-course-road' },
    { name: 'Sohna Road',          slug: 'sohna-road' },
    { name: 'MG Road',             slug: 'mg-road' },
    { name: 'Palam Vihar',         slug: 'palam-vihar' },
    { name: 'Sector 56',           slug: 'sector-56-gurgaon' },
    { name: 'Sector 49',           slug: 'sector-49-gurgaon' },
    { name: 'Sikanderpur',         slug: 'sikanderpur' },
    { name: 'South City',          slug: 'south-city' },
    { name: 'Nirvana Country',     slug: 'nirvana-country' },
    { name: 'Cyber City',          slug: 'cyber-city' },
    { name: 'Udyog Vihar',         slug: 'udyog-vihar' },
    { name: 'Manesar',             slug: 'manesar' },
    { name: 'Surajkund',           slug: 'surajkund' },
  ],

  // ─── JAIPUR ───────────────────────────────────────────────────────────────
  'jaipur': [
    { name: 'MI Road',             slug: 'mi-road' },
    { name: 'Malviya Nagar',       slug: 'malviya-nagar' },
    { name: 'Vaishali Nagar',      slug: 'vaishali-nagar' },
    { name: 'C-Scheme',            slug: 'c-scheme' },
    { name: 'Gopalpura',           slug: 'gopalpura' },
    { name: 'Lal Kothi',           slug: 'lal-kothi' },
    { name: 'New Colony Jaipur',   slug: 'new-colony-jaipur' },
    { name: 'Sanganer',            slug: 'sanganer' },
    { name: 'Jagatpura',           slug: 'jagatpura' },
    { name: 'Malviya Nagar Jaipur', slug: 'malviya-nagar-jaipur' },
    { name: 'Vaishali Nagar Jaipur', slug: 'vaishali-nagar-jaipur' },
    { name: 'Gangori Bazar',       slug: 'gangori-bazar' },
    { name: 'Rajwada',             slug: 'rajwada' },
    { name: 'Bhankrota',           slug: 'bhankrota' },
    { name: 'Tonk Road',           slug: 'tonk-road' },
    { name: 'Bani Park',           slug: 'bani-park' },
    { name: 'Shastri Nagar',       slug: 'shastri-nagar' },
    { name: 'Raja Park',           slug: 'raja-park' },
    { name: 'Sikar Road',          slug: 'sikar-road' },
    { name: 'Sodala',              slug: 'sodala' },
  ],

  // ─── LUCKNOW ──────────────────────────────────────────────────────────────
  'lucknow': [
    { name: 'Hazratganj',          slug: 'hazratganj' },
    { name: 'Gomti Nagar',         slug: 'gomti-nagar' },
    { name: 'Aliganj',             slug: 'aliganj' },
    { name: 'Civil Lines Lucknow', slug: 'civil-lines-lucknow' },
    { name: 'Shaheed Path',        slug: 'shaheed-path' },
    { name: 'Alamnagar',           slug: 'alamnagar' },
    { name: 'Vrindavan Colony',    slug: 'vrindavan-colony' },
    { name: 'Rajendra Nagar Lucknow', slug: 'rajendra-nagar-lucknow' },
    { name: 'Jail Road Lucknow',   slug: 'jail-road-lucknow' },
    { name: 'Kalyanpur Lucknow',   slug: 'kalyanpur-lucknow' },
    { name: 'Nishat Ganj',         slug: 'nishat-ganj' },
    { name: 'LDA Colony',          slug: 'lda-colony' },
    { name: 'Sarojini Nagar Lucknow', slug: 'sarojini-nagar-lucknow' },
    { name: 'Thakurganj',          slug: 'thakurganj' },
    { name: 'Jankipuram Extension', slug: 'jankipuram-extension' },
    { name: 'Jankipuram Vistar',   slug: 'jankipurm-vistar' },
    { name: 'Itaunja',             slug: 'itaunja' },
    { name: 'Kakori',              slug: 'kakori' },
    { name: 'Faizabad Road',       slug: 'faizabad-road' },
    { name: 'Chinhat',             slug: 'chinhat' },
    { name: 'Mohanlalganj',        slug: 'mohanlalganj' },
    { name: 'Charbagh',            slug: 'charbagh' },
    { name: 'Rajajipuram',         slug: 'rajajipuram' },
    { name: 'Viraj Khand',         slug: 'viraj-khand' },
    { name: 'Triveni Nagar',       slug: 'triveni-nagar' },
    { name: 'Mohibullapur',        slug: 'mohibullapur' },
    { name: 'Kalyanpur East',      slug: 'kalyanpur-east' },
    { name: 'Kalli Pashchim',      slug: 'kalli-pashchim' },
    { name: 'Telibagh',            slug: 'telibagh' },
    { name: 'Takrohi',             slug: 'takrohi' },
    { name: 'Dubagga',             slug: 'dubagga' },
    { name: 'Raebareli Road',      slug: 'raebareli-road' },
    { name: 'Nilmatha',            slug: 'nilmatha' },
  ],

  // ─── GOA ──────────────────────────────────────────────────────────────────
  'goa': [
    { name: 'Calangute',           slug: 'calangute' },
    { name: 'Baga',                slug: 'baga' },
    { name: 'Candolim',            slug: 'candolim' },
    { name: 'Panaji',              slug: 'panaji' },
    { name: 'Vagator',             slug: 'vagator' },
    { name: 'Anjuna',              slug: 'anjuna' },
    { name: 'North Goa',           slug: 'north-goa' },
    { name: 'Siridao Beach',       slug: 'siridao-beach' },
    { name: 'Morjim Beach',        slug: 'morjim-beach' },
    { name: 'Mobor Beach',         slug: 'mobor-beach' },
    { name: 'Kakolem Beach',       slug: 'kakolem-beach' },
    { name: 'Chapora Beach',       slug: 'chapora-beach' },
    { name: 'Palolem Beach',       slug: 'palolem-beach' },
    { name: 'Aguada Beach',        slug: 'aguada-beach' },
    { name: 'Ashwem Beach',        slug: 'ashwem-beach' },
    { name: 'Betalbatim Beach',    slug: 'betalbatim-beach' },
    { name: 'Cavelossim Beach',    slug: 'cavelossim-beach' },
    { name: 'Patnem Beach',        slug: 'patnem-beach' },
    { name: 'Chapora Fort',        slug: 'chapora-fort' },
    { name: 'Cabo de Rama Beach',  slug: 'cabo-de-rama-beach' },
    { name: 'Madgaon',             slug: 'madgaon' },
    { name: 'Mapusa Market',       slug: 'mapusa-market' },
    { name: 'Panjim',              slug: 'panjim' },
  ],

  // ─── CHANDIGARH ───────────────────────────────────────────────────────────
  'chandigarh': [
    { name: 'Sector 17',           slug: 'sector-17' },
    { name: 'Sector 22',           slug: 'sector-22' },
    { name: 'Sector 35',           slug: 'sector-35' },
    { name: 'Sector 43',           slug: 'sector-43' },
    { name: 'Sector 9',            slug: 'sector-9' },
    { name: 'Sector 11',           slug: 'sector-11' },
    { name: 'Manimajra',           slug: 'manimajra' },
    { name: 'Panchkula',           slug: 'panchkula' },
    { name: 'Mohali',              slug: 'mohali' },
    { name: 'Zirakpur',            slug: 'zirakpur' },
    { name: 'Kharar',              slug: 'kharar' },
  ],

  // ─── SURAT ────────────────────────────────────────────────────────────────
  'surat': [
    { name: 'Adajan',              slug: 'adajan' },
    { name: 'Katargam',            slug: 'katargam' },
    { name: 'Varachha',            slug: 'varachha' },
    { name: 'Althan',              slug: 'althan' },
    { name: 'Sachin',              slug: 'sachin' },
    { name: 'Limbayat',            slug: 'limbayat' },
    { name: 'Udhna',               slug: 'udhna' },
    { name: 'Chalthan',            slug: 'chalthan' },
    { name: 'Kosamba',             slug: 'kosamba' },
    { name: 'Tandalja',            slug: 'tandalja' },
    { name: 'Variav',              slug: 'variav' },
    { name: 'Dindoli',             slug: 'dindoli' },
    { name: 'Kadodara',            slug: 'kadodara' },
    { name: 'Pardi',               slug: 'pardi' },
    { name: 'Magdalla',            slug: 'magdalla' },
    { name: 'Sayan',               slug: 'sayan' },
    { name: 'Parvat Patiya',       slug: 'parvat-patiya' },
    { name: 'Kosad',               slug: 'kosad' },
    { name: 'Ichchhapor',          slug: 'ichchhapor' },
    { name: 'Nana Varachha',       slug: 'nana-varachha' },
    { name: 'Rundh',               slug: 'rundh' },
    { name: 'Rundh Magdalla',      slug: 'rundh-magdalla' },
    { name: 'Bhestan',             slug: 'bhestan' },
    { name: 'Pal Gam',             slug: 'pal-gam' },
    { name: 'Kapodra',             slug: 'kapodra' },
    { name: 'Dumas',               slug: 'dumas' },
    { name: 'Ghod Dod Road',       slug: 'ghod-dod-road' },
    { name: 'Ring Road',           slug: 'ring-road' },
    { name: 'Pankore Naka',        slug: 'pankore-naka' },
    { name: 'Geeta Mandir Road',   slug: 'geeta-mandir-road' },
    { name: 'Dudheshwar Road',     slug: 'dudheshwar-road' },
    { name: 'Shah Alam Road',      slug: 'shah-alam-road' },
    { name: 'Warasiya',            slug: 'warasiya' },
  ],

  // ─── INDORE ───────────────────────────────────────────────────────────────
  'indore': [
    { name: 'MG Road',             slug: 'mg-road' },
    { name: 'Vijay Nagar',         slug: 'vijay-nagar' },
    { name: 'Sudama Nagar',        slug: 'sudama-nagar' },
    { name: 'Scheme No 54',        slug: 'scheme-no-54' },
    { name: 'Sapna Sangeeta Road', slug: 'sapna-sangeeta-road' },
    { name: 'Old Palasia',         slug: 'old-palasia' },
    { name: 'Manik Bagh Road',     slug: 'manik-bagh-road' },
    { name: 'Neelbad',             slug: 'neelbad' },
    { name: 'Rachna Nagar',        slug: 'rachna-nagar' },
    { name: 'Janjeerwala Square',  slug: 'janjeerwala-square' },
    { name: 'C21 Mall',            slug: 'c21-mall' },
    { name: 'Indore MG Road',      slug: 'indore-mg-road' },
    { name: 'Sanyogitaganj',       slug: 'sanyogitaganj' },
    { name: 'Palasia',             slug: 'palasia' },
    { name: 'Bhawarkuan',          slug: 'bhawarkuan' },
    { name: 'Lasudia Mori',        slug: 'lasudia-mori' },
    { name: 'Super Corridor',      slug: 'super-corridor' },
    { name: 'Niranjanpur Circle',  slug: 'niranjanpur-circle' },
    { name: 'Kanadia',             slug: 'kanadia' },
    { name: 'Pardeshipura',        slug: 'pardeshipura' },
    { name: 'Tukoganj',            slug: 'tukoganj' },
    { name: 'Rajwada',             slug: 'rajwada-indore' },
    { name: 'Mhow',                slug: 'mhow' },
    { name: 'Khajrana Road',       slug: 'khajrana-road' },
    { name: 'Dhar Road',           slug: 'dhar-road' },
    { name: 'Hosangabad Road',     slug: 'hosangabad-road' },
    { name: 'Minal Residency',     slug: 'minal-residency' },
  ],

  // ─── KOCHI ────────────────────────────────────────────────────────────────
  'kochi': [
    { name: 'MG Road',             slug: 'mg-road' },
    { name: 'Edapally',            slug: 'edapally' },
    { name: 'Kakkanad',            slug: 'kakkanad' },
    { name: 'Vyttila',             slug: 'vyttila' },
    { name: 'Aluva',               slug: 'aluva' },
    { name: 'Fort Kochi',          slug: 'fort-kochi' },
    { name: 'Palarivattom',        slug: 'palarivattom' },
    { name: 'Kaloor',              slug: 'kaloor' },
    { name: 'Thammanam',           slug: 'thammanam' },
    { name: 'Vytilla',             slug: 'vytilla' },
    { name: 'Thrikkakara',         slug: 'thrikkakara' },
  ],

  // ─── PUNE NEARBY (NAVI MUMBAI) ────────────────────────────────────────────
  'navi-mumbai': [
    { name: 'Vashi',               slug: 'vashi' },
    { name: 'Nerul',               slug: 'nerul' },
    { name: 'Belapur',             slug: 'belapur' },
    { name: 'Kharghar',            slug: 'kharghar' },
    { name: 'Panvel',              slug: 'panvel' },
    { name: 'Airoli',              slug: 'airoli' },
    { name: 'Ghansoli',            slug: 'ghansoli' },
    { name: 'Kopar Khairane',      slug: 'kopar-khairane' },
    { name: 'Seawood',             slug: 'seawood' },
    { name: 'Sanpada',             slug: 'sanpada' },
    { name: 'Rabale',              slug: 'rabale' },
    { name: 'Kalamboli',           slug: 'kalamboli' },
  ],

  // ─── THANE ────────────────────────────────────────────────────────────────
  'thane': [
    { name: 'Ghodbunder Road',     slug: 'ghodbunder-road' },
    { name: 'Manpada',             slug: 'manpada' },
    { name: 'Hiranandani Estate',  slug: 'hiranandani-estate' },
    { name: 'Kasarwadavali',       slug: 'kasarwadavali' },
    { name: 'Wagle Estate',        slug: 'wagle-estate' },
    { name: 'Thane West',          slug: 'thane-west' },
    { name: 'Dombivli',            slug: 'dombivli' },
    { name: 'Kalyan',              slug: 'kalyan' },
    { name: 'Ulhasnagar',          slug: 'ulhasnagar' },
    { name: 'Ambernath',           slug: 'ambernath' },
    { name: 'Badlapur',            slug: 'badlapur' },
    { name: 'Titwala',             slug: 'titwala' },
    { name: 'Neral',               slug: 'neral' },
    { name: 'Karjat',              slug: 'karjat' },
  ],

  // ─── VADODARA ─────────────────────────────────────────────────────────────
  'vadodara': [
    { name: 'Alkapuri',            slug: 'alkapuri' },
    { name: 'Fatehganj',           slug: 'fatehganj' },
    { name: 'Sayajigunj',          slug: 'sayajigunj' },
    { name: 'Manjalpur',           slug: 'manjalpur' },
    { name: 'Karelibaug',          slug: 'karelibaug' },
    { name: 'Gotri',               slug: 'gotri' },
    { name: 'Makarpura',           slug: 'makarpura' },
    { name: 'Waghodia Road',       slug: 'waghodia-road' },
    { name: 'Productivity Road',   slug: 'productivity-road' },
    { name: 'Vasna Bhayli Road',   slug: 'vasna-bhayli-road' },
    { name: 'Bhayli',              slug: 'bhayli' },
    { name: 'Bhaili',              slug: 'bhaili' },
    { name: 'Diwalipura',          slug: 'diwalipura' },
    { name: 'Harni',               slug: 'harni' },
    { name: 'Gorwa',               slug: 'gorwa' },
    { name: 'Hari Nagar Vadodara', slug: 'hari-nagar-vadodara' },
    { name: 'Lalbagh',             slug: 'lalbagh' },
    { name: 'Sayajiganj',          slug: 'sayajiganj' },
    { name: 'New Sama',            slug: 'new-sama' },
    { name: 'Undera',              slug: 'undera' },
    { name: 'Padra',               slug: 'padra' },
    { name: 'Koyali',              slug: 'koyali' },
    { name: 'Ranoli',              slug: 'ranoli' },
    { name: 'Fulenagar',           slug: 'fulenagar' },
  ],

  // ─── RAJKOT ───────────────────────────────────────────────────────────────
  'rajkot': [
    { name: 'Kalawad Road',        slug: 'kalawad-road' },
    { name: 'Gondal Road',         slug: 'gondal-road' },
    { name: 'University Road',     slug: 'university-road' },
    { name: 'Hari Nagar Rajkot',   slug: 'hari-nagar-rajkot' },
    { name: 'Nana Mava',           slug: 'nana-mava' },
    { name: 'Mavdi',               slug: 'mavdi' },
    { name: 'Mota Mava',           slug: 'mota-mava' },
    { name: 'Vaishali Nagar Rajkot', slug: 'vaishali-nagar-rajkot' },
    { name: 'Raiya',               slug: 'raiya' },
    { name: 'Laska',               slug: 'laska' },
    { name: 'Bhuthnath',           slug: 'bhuthnath' },
    { name: 'Dhoraji',             slug: 'dhoraji' },
    { name: 'Panchvati',           slug: 'panchvati' },
    { name: 'Madhapar',            slug: 'madhapar' },
    { name: 'Ghanteshwer',         slug: 'ghanteshwer' },
    { name: 'Khirasara',           slug: 'khirasara' },
    { name: 'Kotharia',            slug: 'kotharia' },
  ],

  // ─── PATNA ────────────────────────────────────────────────────────────────
  'patna': [
    { name: 'Patna Junction',      slug: 'patna-junction' },
    { name: 'Bailey Road',         slug: 'bailey-road' },
    { name: 'Boring Road',         slug: 'boring-road' },
    { name: 'Kankarbagh',          slug: 'kankarbagh' },
    { name: 'Rajendra Nagar',      slug: 'rajendra-nagar' },
    { name: 'Patliputra Colony',   slug: 'patliputra-colony' },
    { name: 'Fraser Road',         slug: 'fraser-road' },
    { name: 'Exhibition Road',     slug: 'exhibition-road' },
    { name: 'Danapur',             slug: 'danapur' },
    { name: 'Gangapur',            slug: 'gangapur' },
    { name: 'Dakbangla Chauraha',  slug: 'dakbangla-chauraha' },
    { name: 'Kanpur Road',         slug: 'kanpur-road' },
    { name: 'Lanka',               slug: 'lanka' },
  ],

  // ─── KANPUR ───────────────────────────────────────────────────────────────
  'kanpur': [
    { name: 'Civil Lines Kanpur',  slug: 'civil-lines-kanpur' },
    { name: 'Panki',               slug: 'panki' },
    { name: 'Jajmau',              slug: 'jajmau' },
    { name: 'Chakeri',             slug: 'chakeri' },
    { name: 'Govind Nagar',        slug: 'govind-nagar' },
    { name: 'Kidwai Nagar',        slug: 'kidwai-nagar' },
    { name: 'Kalyanpur',           slug: 'kalyanpur' },
    { name: 'Shastri Nagar',       slug: 'shastri-nagar' },
    { name: 'Arya Nagar',          slug: 'arya-nagar' },
    { name: 'Tilak Nagar',         slug: 'tilak-nagar' },
  ],

  // ─── NAGPUR ───────────────────────────────────────────────────────────────
  'nagpur': [
    { name: 'Dharampeth',          slug: 'dharampeth' },
    { name: 'Sadar',               slug: 'sadar' },
    { name: 'Sitabuldi',           slug: 'sitabuldi' },
    { name: 'Ramdaspeth',          slug: 'ramdaspeth' },
    { name: 'Wardhman Nagar',      slug: 'wardhman-nagar' },
    { name: 'Mankapur',            slug: 'mankapur' },
    { name: 'Pratap Nagar',        slug: 'pratap-nagar' },
    { name: 'Hingna Road',         slug: 'hingna-road' },
    { name: 'MIDC',                slug: 'midc-nagpur' },
    { name: 'Wadi',                slug: 'wadi' },
    { name: 'Kamptee Road',        slug: 'kamptee-road' },
  ],

  // ─── BHOPAL ───────────────────────────────────────────────────────────────
  'bhopal': [
    { name: 'MP Nagar',            slug: 'mp-nagar' },
    { name: 'Kolar Road',          slug: 'kolar-road' },
    { name: 'Arera Colony',        slug: 'arera-colony' },
    { name: 'Shyamala Hills',      slug: 'shyamala-hills' },
    { name: 'Piplani',             slug: 'piplani' },
    { name: 'Govindpura',          slug: 'govindpura' },
    { name: 'New Market',          slug: 'new-market-bhopal' },
    { name: 'Ayodhya Nagar',       slug: 'ayodhya-nagar' },
    { name: 'Habibganj',           slug: 'habibganj' },
    { name: 'Misrod',              slug: 'misrod' },
    { name: 'Hosangabad',          slug: 'hosangabad' },
    { name: 'Mahatma Nagar',       slug: 'mahatma-nagar' },
  ],

  // ─── NASHIK ───────────────────────────────────────────────────────────────
  'nashik': [
    { name: 'Canada Corner',       slug: 'canada-corner' },
    { name: 'Deolali',             slug: 'deolali' },
    { name: 'Gangapur Road',       slug: 'gangapur-road' },
    { name: 'Indira Nagar Nashik', slug: 'indira-nagar-nashik' },
    { name: 'Shalimar Nashik',     slug: 'shalimar-nashik' },
    { name: 'Panchavati',          slug: 'panchavati' },
    { name: 'Dindori Road',        slug: 'dindori-road' },
    { name: 'Ambad',               slug: 'ambad' },
    { name: 'Satpur',              slug: 'satpur' },
    { name: 'Mahalakshmi Nagar',   slug: 'mahalakshmi-nagar' },
  ],

  // ─── VARANASI ─────────────────────────────────────────────────────────────
  'varanasi': [
    { name: 'Varanasi Cant',       slug: 'varanasi-cant' },
    { name: 'Godowlia',            slug: 'godowlia' },
    { name: 'Lanka',               slug: 'lanka-varanasi' },
    { name: 'Sigra',               slug: 'sigra' },
    { name: 'Ashapur',             slug: 'ashapur' },
    { name: 'Sarnath',             slug: 'sarnath' },
    { name: 'Shivpur',             slug: 'shivpur' },
    { name: 'Orderly Bazaar',      slug: 'orderly-bazaar' },
  ],

  // ─── AGRA ─────────────────────────────────────────────────────────────────
  'agra': [
    { name: 'Taj Ganj',            slug: 'taj-ganj' },
    { name: 'Shahganj',            slug: 'shahganj' },
    { name: 'Bodla',               slug: 'bodla' },
    { name: 'Kamla Nagar',         slug: 'kamla-nagar-agra' },
    { name: 'Sikandra',            slug: 'sikandra' },
    { name: 'Fatehabad Road',      slug: 'fatehabad-road' },
  ],

  // ─── PRAYAGRAJ ────────────────────────────────────────────────────────────
  'prayagraj': [
    { name: 'Civil Lines',         slug: 'civil-lines' },
    { name: 'George Town',         slug: 'george-town' },
    { name: 'Naini',               slug: 'naini' },
    { name: 'Phaphamau',           slug: 'phaphamau' },
    { name: 'Stanley Road',        slug: 'stanley-road' },
    { name: 'Katra',               slug: 'katra-prayagraj' },
    { name: 'Mumfordganj',         slug: 'mumfordganj' },
  ],

  // ─── GURGAON (HARYANA) ────────────────────────────────────────────────────
  'gurgaon': [
    { name: 'DLF Phase 1',         slug: 'dlf-phase-1' },
    { name: 'DLF Phase 4',         slug: 'dlf-phase-4' },
    { name: 'Golf Course Road',    slug: 'golf-course-road' },
    { name: 'Sohna Road',          slug: 'sohna-road' },
    { name: 'MG Road',             slug: 'mg-road' },
    { name: 'Palam Vihar',         slug: 'palam-vihar' },
    { name: 'Sector 49',           slug: 'sector-49' },
    { name: 'Sector 56',           slug: 'sector-56' },
    { name: 'South City',          slug: 'south-city' },
    { name: 'Sikanderpur',         slug: 'sikanderpur' },
    { name: 'Cyber City',          slug: 'cyber-city' },
    { name: 'Udyog Vihar',         slug: 'udyog-vihar' },
  ],

  // ─── GHAZIABAD ────────────────────────────────────────────────────────────
  'ghaziabad': [
    { name: 'Indirapuram',         slug: 'indirapuram' },
    { name: 'Vaishali',            slug: 'vaishali' },
    { name: 'Raj Nagar Extension', slug: 'raj-nagar-extension' },
    { name: 'Kaushambi',           slug: 'kaushambi' },
    { name: 'Vasundhara',          slug: 'vasundhara' },
    { name: 'Mohan Nagar',         slug: 'mohan-nagar' },
    { name: 'Sanjay Nagar',        slug: 'sanjay-nagar' },
    { name: 'Link Road',           slug: 'link-road' },
  ],

  // ─── FARIDABAD ────────────────────────────────────────────────────────────
  'faridabad': [
    { name: 'Sector 12',           slug: 'sector-12-faridabad' },
    { name: 'NIT Faridabad',       slug: 'nit-faridabad' },
    { name: 'Old Faridabad',       slug: 'old-faridabad' },
    { name: 'Neharpar',            slug: 'neharpar' },
    { name: 'Badarpur',            slug: 'badarpur' },
    { name: 'Greenfields',         slug: 'greenfields' },
  ],

  // ─── LUDHIANA ─────────────────────────────────────────────────────────────
  'ludhiana': [
    { name: 'Model Town',          slug: 'model-town-ludhiana' },
    { name: 'BRS Nagar',           slug: 'brs-nagar' },
    { name: 'Sarabha Nagar',       slug: 'sarabha-nagar' },
    { name: 'Dugri',               slug: 'dugri' },
    { name: 'Civil Lines',         slug: 'civil-lines-ludhiana' },
    { name: 'Focal Point',         slug: 'focal-point' },
    { name: 'Gurdev Nagar',        slug: 'gurdev-nagar' },
  ],

  // ─── AMRITSAR ─────────────────────────────────────────────────────────────
  'amritsar': [
    { name: 'Lawrence Road',       slug: 'lawrence-road' },
    { name: 'Ranjit Avenue',       slug: 'ranjit-avenue' },
    { name: 'Green Avenue',        slug: 'green-avenue' },
    { name: 'Golden Temple',       slug: 'golden-temple' },
    { name: 'Mall Road Amritsar',  slug: 'mall-road-amritsar' },
    { name: 'Queens Road',         slug: 'queens-road' },
  ],

  // ─── COIMBATORE ───────────────────────────────────────────────────────────
  'coimbatore': [
    { name: 'RS Puram',            slug: 'rs-puram' },
    { name: 'Peelamedu',           slug: 'peelamedu' },
    { name: 'Gandhipuram',         slug: 'gandhipuram' },
    { name: 'Saibaba Colony',      slug: 'saibaba-colony' },
    { name: 'Singanallur',         slug: 'singanallur' },
    { name: 'Ukkadam',             slug: 'ukkadam' },
    { name: 'Race Course',         slug: 'race-course' },
  ],

  // ─── JODHPUR ──────────────────────────────────────────────────────────────
  'jodhpur': [
    { name: 'Paota',               slug: 'paota' },
    { name: 'Shastri Nagar',       slug: 'shastri-nagar-jodhpur' },
    { name: 'Sardarpura',          slug: 'sardarpura' },
    { name: 'Ratanada',            slug: 'ratanada' },
    { name: 'Pal Road',            slug: 'pal-road' },
    { name: 'Chopasni Housing Board', slug: 'chopasni' },
    { name: 'Residency Road',      slug: 'residency-road' },
  ],

  // ─── RAIPUR ───────────────────────────────────────────────────────────────
  'raipur': [
    { name: 'Shankar Nagar',       slug: 'shankar-nagar' },
    { name: 'GE Road',             slug: 'ge-road' },
    { name: 'Pandri',              slug: 'pandri' },
    { name: 'Telibandha',          slug: 'telibandha' },
    { name: 'Tikrapara',           slug: 'tikrapara' },
    { name: 'Khamardih',           slug: 'khamardih' },
    { name: 'Avanti Vihar',        slug: 'avanti-vihar' },
  ],

  // ─── DEHRADUN ─────────────────────────────────────────────────────────────
  'dehradun': [
    { name: 'Rajpur Road',         slug: 'rajpur-road' },
    { name: 'New Cantt Road',      slug: 'new-cantt-road' },
    { name: 'Sahaspur',            slug: 'sahaspur' },
    { name: 'Prem Nagar',          slug: 'prem-nagar' },
    { name: 'Vasant Vihar',        slug: 'vasant-vihar-dehradun' },
    { name: 'Dharampur',           slug: 'dharampur' },
    { name: 'IMA Road',            slug: 'ima-road' },
  ],

  // ─── UDAIPUR ──────────────────────────────────────────────────────────────
  'udaipur': [
    { name: 'Fateh Sagar',         slug: 'fateh-sagar' },
    { name: 'City Palace',         slug: 'city-palace-udaipur' },
    { name: 'Suraj Pol',           slug: 'suraj-pol' },
    { name: 'Hiran Magri',         slug: 'hiran-magri' },
    { name: 'Bhuwana',             slug: 'bhuwana' },
  ],

  // ─── MYSORE ───────────────────────────────────────────────────────────────
  'mysore': [
    { name: 'Jayalakshmipuram',    slug: 'jayalakshmipuram' },
    { name: 'Vijayanagar',         slug: 'vijayanagar-mysore' },
    { name: 'Kuvempunagar',        slug: 'kuvempunagar' },
    { name: 'Gokulam',             slug: 'gokulam' },
    { name: 'Saraswathipuram',     slug: 'saraswathipuram' },
    { name: 'Nazarbad',            slug: 'nazarbad' },
  ],

  // ─── RANCHI ───────────────────────────────────────────────────────────────
  'ranchi': [
    { name: 'Doranda',             slug: 'doranda' },
    { name: 'Lalpur',              slug: 'lalpur' },
    { name: 'Harmu',               slug: 'harmu' },
    { name: 'Hinoo',               slug: 'hinoo' },
    { name: 'Bariatu',             slug: 'bariatu' },
    { name: 'Morabadi',            slug: 'morabadi' },
  ],

  // ─── BHUBANESWAR ──────────────────────────────────────────────────────────
  'bhubaneswar': [
    { name: 'Saheed Nagar',        slug: 'saheed-nagar' },
    { name: 'Patia',               slug: 'patia' },
    { name: 'Nayapalli',           slug: 'nayapalli' },
    { name: 'Jaydev Vihar',        slug: 'jaydev-vihar' },
    { name: 'Kharavel Nagar',      slug: 'kharavel-nagar' },
    { name: 'Rasulgarh',           slug: 'rasulgarh' },
    { name: 'Chandrasekharpur',    slug: 'chandrasekharpur' },
  ],

  // ─── VISAKHAPATNAM ────────────────────────────────────────────────────────
  'visakhapatnam': [
    { name: 'Steel Plant',         slug: 'steel-plant' },
    { name: 'Dwaraka Nagar',       slug: 'dwaraka-nagar' },
    { name: 'Siripuram',           slug: 'siripuram' },
    { name: 'MVP Colony',          slug: 'mvp-colony' },
    { name: 'Rushikonda',          slug: 'rushikonda' },
    { name: 'Gajuwaka',            slug: 'gajuwaka' },
    { name: 'Madhurawada',         slug: 'madhurawada' },
  ],

  // ─── PIMPRI-CHINCHWAD ─────────────────────────────────────────────────────
  'pimpri-chinchwad': [
    { name: 'Chinchwad',           slug: 'chinchwad' },
    { name: 'Pimpri',              slug: 'pimpri' },
    { name: 'Akurdi',              slug: 'akurdi' },
    { name: 'Nigdi',               slug: 'nigdi' },
    { name: 'Bhosari',             slug: 'bhosari' },
    { name: 'Chakan',              slug: 'chakan' },
    { name: 'Talegaon',            slug: 'talegaon' },
  ],

  // ─── KOLHAPUR ─────────────────────────────────────────────────────────────
  'kolhapur': [
    { name: 'Rajarampuri',         slug: 'rajarampuri' },
    { name: 'Shivaji Peth',        slug: 'shivaji-peth' },
    { name: 'Tarabai Park',        slug: 'tarabai-park' },
    { name: 'Kasba Bavada',        slug: 'kasba-bavada' },
    { name: 'Shahupuri',           slug: 'shahupuri' },
  ],

  // ─── SOLAPUR ──────────────────────────────────────────────────────────────
  'solapur': [
    { name: 'Hotgi Road',          slug: 'hotgi-road' },
    { name: 'Hutatma Chowk',       slug: 'hutatma-chowk' },
    { name: 'Vijay Nagar Solapur', slug: 'vijay-nagar-solapur' },
  ],

  // ─── SILIGURI ─────────────────────────────────────────────────────────────
  'siliguri': [
    { name: 'Hill Cart Road',      slug: 'hill-cart-road' },
    { name: 'Sevoke Road',         slug: 'sevoke-road' },
    { name: 'Hakimpara',           slug: 'hakimpara' },
    { name: 'Matigara',            slug: 'matigara' },
  ],

  // ─── VIJAYAWADA ───────────────────────────────────────────────────────────
  'vijayawada': [
    { name: 'Governorpet',         slug: 'governorpet' },
    { name: 'Benz Circle',         slug: 'benz-circle' },
    { name: 'Suryaraopet',         slug: 'suryaraopet' },
    { name: 'Auto Nagar',          slug: 'auto-nagar' },
  ],

  // ─── THIRUVANANTHAPURAM ───────────────────────────────────────────────────
  'thiruvananthapuram': [
    { name: 'Kowdiar',             slug: 'kowdiar' },
    { name: 'Pattom',              slug: 'pattom' },
    { name: 'Vanchiyoor',          slug: 'vanchiyoor' },
    { name: 'Kesavadasapuram',     slug: 'kesavadasapuram' },
    { name: 'Kazhakuttam',         slug: 'kazhakuttam' },
  ],

  // ─── AURANGABAD ───────────────────────────────────────────────────────────
  'aurangabad': [
    { name: 'Cidco',               slug: 'cidco' },
    { name: 'Garkheda',            slug: 'garkheda' },
    { name: 'Pundaliknagar',       slug: 'pundaliknagar' },
    { name: 'Bajaj Nagar',         slug: 'bajaj-nagar-aurangabad' },
    { name: 'N-5 CIDCO',           slug: 'n5-cidco' },
  ],

  // ─── MADURAI ──────────────────────────────────────────────────────────────
  'madurai': [
    { name: 'Anna Nagar Madurai',  slug: 'anna-nagar-madurai' },
    { name: 'KK Nagar',            slug: 'kk-nagar' },
    { name: 'Iyer Bungalow',       slug: 'iyer-bungalow' },
    { name: 'Tallakulam',          slug: 'tallakulam' },
    { name: 'Villapuram',          slug: 'villapuram' },
  ],

  // ─── PONDICHERRY ──────────────────────────────────────────────────────────
  'pondicherry': [
    { name: 'White Town',          slug: 'white-town' },
    { name: 'Reddiyarpalayam',     slug: 'reddiyarpalayam' },
    { name: 'Lawspet',             slug: 'lawspet' },
    { name: 'Villianur',           slug: 'villianur' },
    { name: 'Mudaliarpet',         slug: 'mudaliarpet' },
  ],

  // ─── AJMER ────────────────────────────────────────────────────────────────
  'ajmer': [
    { name: 'Vaishali Nagar Ajmer', slug: 'vaishali-nagar-ajmer' },
    { name: 'Prithviraj Nagar',    slug: 'prithviraj-nagar' },
    { name: 'Nasirabad',           slug: 'nasirabad' },
    { name: 'Ramganj',             slug: 'ramganj' },
    { name: 'Civil Lines Ajmer',   slug: 'civil-lines-ajmer' },
  ],
};

// Build area lookup: citySlug → { areaSlug → area }
const AREA_BY_SLUG = {};
Object.entries(AREAS).forEach(([citySlug, areas]) => {
  AREA_BY_SLUG[citySlug] = areas.reduce((map, area) => {
    map[area.slug] = area;
    return map;
  }, {});
});

const getAreasForCity = (citySlug) => AREAS[citySlug] || [];
const getArea = (citySlug, areaSlug) => (AREA_BY_SLUG[citySlug] || {})[areaSlug] || null;

module.exports = { AREAS, AREA_BY_SLUG, getAreasForCity, getArea };
