// 70+ Indian cities for escort service location pages
const CITIES = [
  // Metro Cities
  { name: 'Delhi',            slug: 'delhi',            state: 'Delhi',             metro: true,  lat: 28.6139, lon: 77.2090 },
  { name: 'Mumbai',           slug: 'mumbai',           state: 'Maharashtra',       metro: true,  lat: 19.0760, lon: 72.8777 },
  { name: 'Bangalore',        slug: 'bangalore',        state: 'Karnataka',         metro: true,  lat: 12.9716, lon: 77.5946 },
  { name: 'Hyderabad',        slug: 'hyderabad',        state: 'Telangana',         metro: true,  lat: 17.3850, lon: 78.4867 },
  { name: 'Chennai',          slug: 'chennai',          state: 'Tamil Nadu',        metro: true,  lat: 13.0827, lon: 80.2707 },
  { name: 'Kolkata',          slug: 'kolkata',          state: 'West Bengal',       metro: true,  lat: 22.5726, lon: 88.3639 },
  { name: 'Pune',             slug: 'pune',             state: 'Maharashtra',       metro: true,  lat: 18.5204, lon: 73.8567 },
  { name: 'Ahmedabad',        slug: 'ahmedabad',        state: 'Gujarat',           metro: true,  lat: 23.0225, lon: 72.5714 },
  { name: 'Noida',            slug: 'noida',            state: 'Uttar Pradesh',     metro: true,  lat: 28.5355, lon: 77.3910 },
  { name: 'Gurugram',         slug: 'gurugram',         state: 'Haryana',           metro: true,  lat: 28.4595, lon: 77.0266 },

  // Tier-1 Cities
  { name: 'Jaipur',           slug: 'jaipur',           state: 'Rajasthan',         metro: false, lat: 26.9124, lon: 75.7873 },
  { name: 'Surat',            slug: 'surat',            state: 'Gujarat',           metro: false, lat: 21.1702, lon: 72.8311 },
  { name: 'Lucknow',          slug: 'lucknow',          state: 'Uttar Pradesh',     metro: false, lat: 26.8467, lon: 80.9462 },
  { name: 'Kanpur',           slug: 'kanpur',           state: 'Uttar Pradesh',     metro: false },
  { name: 'Nagpur',           slug: 'nagpur',           state: 'Maharashtra',       metro: false },
  { name: 'Indore',           slug: 'indore',           state: 'Madhya Pradesh',    metro: false, lat: 22.7196, lon: 75.8577 },
  { name: 'Thane',            slug: 'thane',            state: 'Maharashtra',       metro: false },
  { name: 'Bhopal',           slug: 'bhopal',           state: 'Madhya Pradesh',    metro: false },
  { name: 'Visakhapatnam',    slug: 'visakhapatnam',    state: 'Andhra Pradesh',    metro: false },
  { name: 'Patna',            slug: 'patna',            state: 'Bihar',             metro: false, lat: 25.5941, lon: 85.1376 },
  { name: 'Vadodara',         slug: 'vadodara',         state: 'Gujarat',           metro: false },
  { name: 'Ghaziabad',        slug: 'ghaziabad',        state: 'Uttar Pradesh',     metro: false },
  { name: 'Ludhiana',         slug: 'ludhiana',         state: 'Punjab',            metro: false },
  { name: 'Agra',             slug: 'agra',             state: 'Uttar Pradesh',     metro: false, lat: 27.1767, lon: 78.0081 },
  { name: 'Nashik',           slug: 'nashik',           state: 'Maharashtra',       metro: false },
  { name: 'Faridabad',        slug: 'faridabad',        state: 'Haryana',           metro: false },
  { name: 'Meerut',           slug: 'meerut',           state: 'Uttar Pradesh',     metro: false },
  { name: 'Rajkot',           slug: 'rajkot',           state: 'Gujarat',           metro: false },
  { name: 'Varanasi',         slug: 'varanasi',         state: 'Uttar Pradesh',     metro: false, lat: 25.3176, lon: 82.9739 },
  { name: 'Amritsar',         slug: 'amritsar',         state: 'Punjab',            metro: false },
  { name: 'Aurangabad',       slug: 'aurangabad',       state: 'Maharashtra',       metro: false },
  { name: 'Ranchi',           slug: 'ranchi',           state: 'Jharkhand',         metro: false, lat: 23.3441, lon: 85.3096 },
  { name: 'Coimbatore',       slug: 'coimbatore',       state: 'Tamil Nadu',        metro: false, lat: 11.0168, lon: 76.9558 },
  { name: 'Jodhpur',          slug: 'jodhpur',          state: 'Rajasthan',         metro: false },
  { name: 'Madurai',          slug: 'madurai',          state: 'Tamil Nadu',        metro: false },
  { name: 'Raipur',           slug: 'raipur',           state: 'Chhattisgarh',      metro: false },
  { name: 'Kochi',            slug: 'kochi',            state: 'Kerala',            metro: false, lat: 9.9312,  lon: 76.2673 },
  { name: 'Chandigarh',       slug: 'chandigarh',       state: 'Punjab',            metro: false, lat: 30.7333, lon: 76.7794 },
  { name: 'Guwahati',         slug: 'guwahati',         state: 'Assam',             metro: false },
  { name: 'Bhubaneswar',      slug: 'bhubaneswar',      state: 'Odisha',            metro: false },
  { name: 'Thiruvananthapuram', slug: 'thiruvananthapuram', state: 'Kerala',        metro: false },
  { name: 'Jabalpur',         slug: 'jabalpur',         state: 'Madhya Pradesh',    metro: false },
  { name: 'Gwalior',          slug: 'gwalior',          state: 'Madhya Pradesh',    metro: false },
  { name: 'Vijayawada',       slug: 'vijayawada',       state: 'Andhra Pradesh',    metro: false },
  { name: 'Prayagraj',        slug: 'prayagraj',        state: 'Uttar Pradesh',     metro: false },
  { name: 'Bareilly',         slug: 'bareilly',         state: 'Uttar Pradesh',     metro: false },
  { name: 'Aligarh',          slug: 'aligarh',          state: 'Uttar Pradesh',     metro: false },
  { name: 'Moradabad',        slug: 'moradabad',        state: 'Uttar Pradesh',     metro: false },
  { name: 'Gurgaon',          slug: 'gurgaon',          state: 'Haryana',           metro: false },
  { name: 'Mysore',           slug: 'mysore',           state: 'Karnataka',         metro: false },
  { name: 'Mangalore',        slug: 'mangalore',        state: 'Karnataka',         metro: false },
  { name: 'Hubli',            slug: 'hubli',            state: 'Karnataka',         metro: false },
  { name: 'Belgaum',          slug: 'belgaum',          state: 'Karnataka',         metro: false },
  { name: 'Kolhapur',         slug: 'kolhapur',         state: 'Maharashtra',       metro: false },
  { name: 'Solapur',          slug: 'solapur',          state: 'Maharashtra',       metro: false },
  { name: 'Navi Mumbai',      slug: 'navi-mumbai',      state: 'Maharashtra',       metro: false },
  { name: 'Pimpri-Chinchwad', slug: 'pimpri-chinchwad', state: 'Maharashtra',       metro: false },
  { name: 'Udaipur',          slug: 'udaipur',          state: 'Rajasthan',         metro: false },
  { name: 'Kota',             slug: 'kota',             state: 'Rajasthan',         metro: false },
  { name: 'Ajmer',            slug: 'ajmer',            state: 'Rajasthan',         metro: false },
  { name: 'Bikaner',          slug: 'bikaner',          state: 'Rajasthan',         metro: false },
  { name: 'Siliguri',         slug: 'siliguri',         state: 'West Bengal',       metro: false },
  { name: 'Jamshedpur',       slug: 'jamshedpur',       state: 'Jharkhand',         metro: false },
  { name: 'Dhanbad',          slug: 'dhanbad',          state: 'Jharkhand',         metro: false },
  { name: 'Warangal',         slug: 'warangal',         state: 'Telangana',         metro: false },
  { name: 'Tirupati',         slug: 'tirupati',         state: 'Andhra Pradesh',    metro: false },
  { name: 'Cuttack',          slug: 'cuttack',          state: 'Odisha',            metro: false },
  { name: 'Dehradun',         slug: 'dehradun',         state: 'Uttarakhand',       metro: false },
  { name: 'Shimla',           slug: 'shimla',           state: 'Himachal Pradesh',  metro: false },
  { name: 'Nainital',         slug: 'nainital',         state: 'Uttarakhand',       metro: false },
  { name: 'Rishikesh',        slug: 'rishikesh',        state: 'Uttarakhand',       metro: false },
  { name: 'Haridwar',         slug: 'haridwar',         state: 'Uttarakhand',       metro: false },
  { name: 'Mussoorie',        slug: 'mussoorie',        state: 'Uttarakhand',       metro: false },
  { name: 'Goa',              slug: 'goa',              state: 'Goa',               metro: false, lat: 15.2993, lon: 74.1240 },
  { name: 'Shillong',         slug: 'shillong',         state: 'Meghalaya',         metro: false },
  { name: 'Imphal',           slug: 'imphal',           state: 'Manipur',           metro: false },
  { name: 'Srinagar',         slug: 'srinagar',         state: 'Jammu & Kashmir',   metro: false },
  { name: 'Jammu',            slug: 'jammu',            state: 'Jammu & Kashmir',   metro: false },
  { name: 'Pondicherry',      slug: 'pondicherry',      state: 'Puducherry',        metro: false },

  // Additional Tier-2 & searched cities
  { name: 'Tiruchirappalli', slug: 'tiruchirappalli',  state: 'Tamil Nadu',        metro: false },
  { name: 'Trichy',          slug: 'trichy',           state: 'Tamil Nadu',        metro: false },
  { name: 'Salem',           slug: 'salem',            state: 'Tamil Nadu',        metro: false },
  { name: 'Tirunelveli',     slug: 'tirunelveli',      state: 'Tamil Nadu',        metro: false },
  { name: 'Vellore',         slug: 'vellore',          state: 'Tamil Nadu',        metro: false },
  { name: 'Erode',           slug: 'erode',            state: 'Tamil Nadu',        metro: false },
  { name: 'Tiruppur',        slug: 'tiruppur',         state: 'Tamil Nadu',        metro: false },
  { name: 'Thrissur',        slug: 'thrissur',         state: 'Kerala',            metro: false },
  { name: 'Kozhikode',       slug: 'kozhikode',        state: 'Kerala',            metro: false },
  { name: 'Kollam',          slug: 'kollam',           state: 'Kerala',            metro: false },
  { name: 'Kannur',          slug: 'kannur',           state: 'Kerala',            metro: false },
  { name: 'Guntur',          slug: 'guntur',           state: 'Andhra Pradesh',    metro: false },
  { name: 'Nellore',         slug: 'nellore',          state: 'Andhra Pradesh',    metro: false },
  { name: 'Kurnool',         slug: 'kurnool',          state: 'Andhra Pradesh',    metro: false },
  { name: 'Kakinada',        slug: 'kakinada',         state: 'Andhra Pradesh',    metro: false },
  { name: 'Rajahmundry',     slug: 'rajahmundry',      state: 'Andhra Pradesh',    metro: false },
  { name: 'Karimnagar',      slug: 'karimnagar',       state: 'Telangana',         metro: false },
  { name: 'Nizamabad',       slug: 'nizamabad',        state: 'Telangana',         metro: false },
  { name: 'Mysuru',          slug: 'mysuru',           state: 'Karnataka',         metro: false },
  { name: 'Gulbarga',        slug: 'gulbarga',         state: 'Karnataka',         metro: false },
  { name: 'Davangere',       slug: 'davangere',        state: 'Karnataka',         metro: false },
  { name: 'Shimoga',         slug: 'shimoga',          state: 'Karnataka',         metro: false },
  { name: 'Tumkur',          slug: 'tumkur',           state: 'Karnataka',         metro: false },
  { name: 'Bilaspur',        slug: 'bilaspur',         state: 'Chhattisgarh',      metro: false },
  { name: 'Korba',           slug: 'korba',            state: 'Chhattisgarh',      metro: false },
  { name: 'Gorakhpur',       slug: 'gorakhpur',        state: 'Uttar Pradesh',     metro: false },
  { name: 'Allahabad',       slug: 'allahabad',        state: 'Uttar Pradesh',     metro: false },
  { name: 'Mathura',         slug: 'mathura',          state: 'Uttar Pradesh',     metro: false },
  { name: 'Firozabad',       slug: 'firozabad',        state: 'Uttar Pradesh',     metro: false },
  { name: 'Saharanpur',      slug: 'saharanpur',       state: 'Uttar Pradesh',     metro: false },
  { name: 'Muzaffarnagar',   slug: 'muzaffarnagar',    state: 'Uttar Pradesh',     metro: false },
  { name: 'Bhilai',          slug: 'bhilai',           state: 'Chhattisgarh',      metro: false },
  { name: 'Durgapur',        slug: 'durgapur',         state: 'West Bengal',       metro: false },
  { name: 'Asansol',         slug: 'asansol',          state: 'West Bengal',       metro: false },
  { name: 'Bokaro',          slug: 'bokaro',           state: 'Jharkhand',         metro: false },
  { name: 'Gaya',            slug: 'gaya',             state: 'Bihar',             metro: false },
  { name: 'Muzaffarpur',     slug: 'muzaffarpur',      state: 'Bihar',             metro: false },
  { name: 'Bhagalpur',       slug: 'bhagalpur',        state: 'Bihar',             metro: false },

  // Tamil Nadu — remaining district HQs & towns
  { name: 'Nagapattinam',    slug: 'nagapattinam',     state: 'Tamil Nadu',        metro: false },
  { name: 'Thanjavur',       slug: 'thanjavur',        state: 'Tamil Nadu',        metro: false },
  { name: 'Dindigul',        slug: 'dindigul',         state: 'Tamil Nadu',        metro: false },
  { name: 'Cuddalore',       slug: 'cuddalore',        state: 'Tamil Nadu',        metro: false },
  { name: 'Thoothukudi',     slug: 'thoothukudi',      state: 'Tamil Nadu',        metro: false },
  { name: 'Tuticorin',       slug: 'tuticorin',        state: 'Tamil Nadu',        metro: false },
  { name: 'Nagercoil',       slug: 'nagercoil',        state: 'Tamil Nadu',        metro: false },
  { name: 'Hosur',           slug: 'hosur',            state: 'Tamil Nadu',        metro: false },
  { name: 'Krishnagiri',     slug: 'krishnagiri',      state: 'Tamil Nadu',        metro: false },
  { name: 'Dharmapuri',      slug: 'dharmapuri',       state: 'Tamil Nadu',        metro: false },
  { name: 'Namakkal',        slug: 'namakkal',         state: 'Tamil Nadu',        metro: false },
  { name: 'Sivakasi',        slug: 'sivakasi',         state: 'Tamil Nadu',        metro: false },
  { name: 'Ramanathapuram',  slug: 'ramanathapuram',   state: 'Tamil Nadu',        metro: false },
  { name: 'Virudhunagar',    slug: 'virudhunagar',     state: 'Tamil Nadu',        metro: false },
  { name: 'Sivagangai',      slug: 'sivagangai',       state: 'Tamil Nadu',        metro: false },
  { name: 'Karur',           slug: 'karur',            state: 'Tamil Nadu',        metro: false },
  { name: 'Ooty',            slug: 'ooty',             state: 'Tamil Nadu',        metro: false },
  { name: 'Kanchipuram',     slug: 'kanchipuram',      state: 'Tamil Nadu',        metro: false },
  { name: 'Tiruvannamalai',  slug: 'tiruvannamalai',   state: 'Tamil Nadu',        metro: false },
  { name: 'Villupuram',      slug: 'villupuram',       state: 'Tamil Nadu',        metro: false },
  { name: 'Pudukkottai',     slug: 'pudukkottai',      state: 'Tamil Nadu',        metro: false },
  { name: 'Chengalpattu',    slug: 'chengalpattu',     state: 'Tamil Nadu',        metro: false },
  { name: 'Ranipet',         slug: 'ranipet',          state: 'Tamil Nadu',        metro: false },
  { name: 'Tenkasi',         slug: 'tenkasi',          state: 'Tamil Nadu',        metro: false },

  // Maharashtra — remaining district HQs
  { name: 'Amravati',        slug: 'amravati',         state: 'Maharashtra',       metro: false },
  { name: 'Akola',           slug: 'akola',            state: 'Maharashtra',       metro: false },
  { name: 'Latur',           slug: 'latur',            state: 'Maharashtra',       metro: false },
  { name: 'Nanded',          slug: 'nanded',           state: 'Maharashtra',       metro: false },
  { name: 'Jalgaon',         slug: 'jalgaon',          state: 'Maharashtra',       metro: false },
  { name: 'Satara',          slug: 'satara',           state: 'Maharashtra',       metro: false },
  { name: 'Sangli',          slug: 'sangli',           state: 'Maharashtra',       metro: false },
  { name: 'Chandrapur',      slug: 'chandrapur',       state: 'Maharashtra',       metro: false },
  { name: 'Yavatmal',        slug: 'yavatmal',         state: 'Maharashtra',       metro: false },

  // Rajasthan — remaining district HQs
  { name: 'Bharatpur',       slug: 'bharatpur',        state: 'Rajasthan',         metro: false },
  { name: 'Alwar',           slug: 'alwar',            state: 'Rajasthan',         metro: false },
  { name: 'Sikar',           slug: 'sikar',            state: 'Rajasthan',         metro: false },
  { name: 'Bhilwara',        slug: 'bhilwara',         state: 'Rajasthan',         metro: false },
  { name: 'Pali',            slug: 'pali',             state: 'Rajasthan',         metro: false },
  { name: 'Barmer',          slug: 'barmer',           state: 'Rajasthan',         metro: false },
  { name: 'Chittorgarh',     slug: 'chittorgarh',      state: 'Rajasthan',         metro: false },
  { name: 'Sri Ganganagar',  slug: 'sri-ganganagar',   state: 'Rajasthan',         metro: false },
  { name: 'Hanumangarh',     slug: 'hanumangarh',      state: 'Rajasthan',         metro: false },

  // Gujarat — remaining cities
  { name: 'Gandhinagar',     slug: 'gandhinagar',      state: 'Gujarat',           metro: false },
  { name: 'Junagadh',        slug: 'junagadh',         state: 'Gujarat',           metro: false },
  { name: 'Bhavnagar',       slug: 'bhavnagar',        state: 'Gujarat',           metro: false },
  { name: 'Anand',           slug: 'anand',            state: 'Gujarat',           metro: false },
  { name: 'Mehsana',         slug: 'mehsana',          state: 'Gujarat',           metro: false },
  { name: 'Porbandar',       slug: 'porbandar',        state: 'Gujarat',           metro: false },
  { name: 'Surendranagar',   slug: 'surendranagar',    state: 'Gujarat',           metro: false },

  // Punjab — remaining cities
  { name: 'Jalandhar',       slug: 'jalandhar',        state: 'Punjab',            metro: false },
  { name: 'Patiala',         slug: 'patiala',          state: 'Punjab',            metro: false },
  { name: 'Bathinda',        slug: 'bathinda',         state: 'Punjab',            metro: false },
  { name: 'Mohali',          slug: 'mohali',           state: 'Punjab',            metro: false },
  { name: 'Pathankot',       slug: 'pathankot',        state: 'Punjab',            metro: false },
  { name: 'Hoshiarpur',      slug: 'hoshiarpur',       state: 'Punjab',            metro: false },
  { name: 'Moga',            slug: 'moga',             state: 'Punjab',            metro: false },

  // Haryana — remaining cities
  { name: 'Ambala',          slug: 'ambala',           state: 'Haryana',           metro: false },
  { name: 'Hisar',           slug: 'hisar',            state: 'Haryana',           metro: false },
  { name: 'Rohtak',          slug: 'rohtak',           state: 'Haryana',           metro: false },
  { name: 'Panipat',         slug: 'panipat',          state: 'Haryana',           metro: false },
  { name: 'Karnal',          slug: 'karnal',           state: 'Haryana',           metro: false },
  { name: 'Sonipat',         slug: 'sonipat',          state: 'Haryana',           metro: false },
  { name: 'Yamunanagar',     slug: 'yamunanagar',      state: 'Haryana',           metro: false },
  { name: 'Bhiwani',         slug: 'bhiwani',          state: 'Haryana',           metro: false },
  { name: 'Rewari',          slug: 'rewari',           state: 'Haryana',           metro: false },
  { name: 'Panchkula',       slug: 'panchkula',        state: 'Haryana',           metro: false },
  { name: 'Kurukshetra',     slug: 'kurukshetra',      state: 'Haryana',           metro: false },

  // Madhya Pradesh — remaining cities
  { name: 'Ujjain',          slug: 'ujjain',           state: 'Madhya Pradesh',    metro: false },
  { name: 'Sagar',           slug: 'sagar',            state: 'Madhya Pradesh',    metro: false },
  { name: 'Satna',           slug: 'satna',            state: 'Madhya Pradesh',    metro: false },
  { name: 'Rewa',            slug: 'rewa',             state: 'Madhya Pradesh',    metro: false },
  { name: 'Dewas',           slug: 'dewas',            state: 'Madhya Pradesh',    metro: false },
  { name: 'Chhindwara',      slug: 'chhindwara',       state: 'Madhya Pradesh',    metro: false },
  { name: 'Khandwa',         slug: 'khandwa',          state: 'Madhya Pradesh',    metro: false },
  { name: 'Burhanpur',       slug: 'burhanpur',        state: 'Madhya Pradesh',    metro: false },

  // Uttar Pradesh — remaining cities
  { name: 'Jhansi',          slug: 'jhansi',           state: 'Uttar Pradesh',     metro: false },
  { name: 'Rampur',          slug: 'rampur',           state: 'Uttar Pradesh',     metro: false },
  { name: 'Bulandshahr',     slug: 'bulandshahr',      state: 'Uttar Pradesh',     metro: false },
  { name: 'Etawah',          slug: 'etawah',           state: 'Uttar Pradesh',     metro: false },
  { name: 'Mainpuri',        slug: 'mainpuri',         state: 'Uttar Pradesh',     metro: false },
  { name: 'Rae Bareli',      slug: 'rae-bareli',       state: 'Uttar Pradesh',     metro: false },
  { name: 'Unnao',           slug: 'unnao',            state: 'Uttar Pradesh',     metro: false },
  { name: 'Jaunpur',         slug: 'jaunpur',          state: 'Uttar Pradesh',     metro: false },
  { name: 'Azamgarh',        slug: 'azamgarh',         state: 'Uttar Pradesh',     metro: false },
  { name: 'Mirzapur',        slug: 'mirzapur',         state: 'Uttar Pradesh',     metro: false },
  { name: 'Sultanpur',       slug: 'sultanpur',        state: 'Uttar Pradesh',     metro: false },

  // Bihar — remaining cities
  { name: 'Darbhanga',       slug: 'darbhanga',        state: 'Bihar',             metro: false },
  { name: 'Purnia',          slug: 'purnia',           state: 'Bihar',             metro: false },
  { name: 'Arrah',           slug: 'arrah',            state: 'Bihar',             metro: false },
  { name: 'Begusarai',       slug: 'begusarai',        state: 'Bihar',             metro: false },
  { name: 'Munger',          slug: 'munger',           state: 'Bihar',             metro: false },
  { name: 'Hajipur',         slug: 'hajipur',          state: 'Bihar',             metro: false },
  { name: 'Chapra',          slug: 'chapra',           state: 'Bihar',             metro: false },
  { name: 'Sitamarhi',       slug: 'sitamarhi',        state: 'Bihar',             metro: false },

  // West Bengal — remaining cities
  { name: 'Howrah',          slug: 'howrah',           state: 'West Bengal',       metro: false },
  { name: 'Bardhaman',       slug: 'bardhaman',        state: 'West Bengal',       metro: false },
  { name: 'Malda',           slug: 'malda',            state: 'West Bengal',       metro: false },
  { name: 'Kharagpur',       slug: 'kharagpur',        state: 'West Bengal',       metro: false },
  { name: 'Haldia',          slug: 'haldia',           state: 'West Bengal',       metro: false },
  { name: 'Midnapore',       slug: 'midnapore',        state: 'West Bengal',       metro: false },

  // Odisha — remaining cities
  { name: 'Rourkela',        slug: 'rourkela',         state: 'Odisha',            metro: false },
  { name: 'Brahmapur',       slug: 'brahmapur',        state: 'Odisha',            metro: false },
  { name: 'Sambalpur',       slug: 'sambalpur',        state: 'Odisha',            metro: false },
  { name: 'Puri',            slug: 'puri',             state: 'Odisha',            metro: false },
  { name: 'Balasore',        slug: 'balasore',         state: 'Odisha',            metro: false },

  // Assam — remaining cities
  { name: 'Dibrugarh',       slug: 'dibrugarh',        state: 'Assam',             metro: false },
  { name: 'Silchar',         slug: 'silchar',          state: 'Assam',             metro: false },
  { name: 'Jorhat',          slug: 'jorhat',           state: 'Assam',             metro: false },
  { name: 'Tezpur',          slug: 'tezpur',           state: 'Assam',             metro: false },

  // Other states
  { name: 'Mangaluru',       slug: 'mangaluru',        state: 'Karnataka',         metro: false },
  { name: 'Belagavi',        slug: 'belagavi',         state: 'Karnataka',         metro: false },
  { name: 'Kalaburagi',      slug: 'kalaburagi',       state: 'Karnataka',         metro: false },
  { name: 'Ballari',         slug: 'ballari',          state: 'Karnataka',         metro: false },
  { name: 'Vijayapura',      slug: 'vijayapura',       state: 'Karnataka',         metro: false },
  { name: 'Alappuzha',       slug: 'alappuzha',        state: 'Kerala',            metro: false },
  { name: 'Palakkad',        slug: 'palakkad',         state: 'Kerala',            metro: false },
  { name: 'Malappuram',      slug: 'malappuram',       state: 'Kerala',            metro: false },
  { name: 'Kasaragod',       slug: 'kasaragod',        state: 'Kerala',            metro: false },
  { name: 'Kottayam',        slug: 'kottayam',         state: 'Kerala',            metro: false },
  { name: 'Idukki',          slug: 'idukki',           state: 'Kerala',            metro: false },
  { name: 'Agartala',        slug: 'agartala',         state: 'Tripura',           metro: false },
  { name: 'Aizawl',          slug: 'aizawl',           state: 'Mizoram',           metro: false },
  { name: 'Itanagar',        slug: 'itanagar',         state: 'Arunachal Pradesh', metro: false },
  { name: 'Kohima',          slug: 'kohima',           state: 'Nagaland',          metro: false },
  { name: 'Panaji',          slug: 'panaji',           state: 'Goa',               metro: false, lat: 15.4989, lon: 73.8278 },
  { name: 'Margao',          slug: 'margao',           state: 'Goa',               metro: false },
  { name: 'Leh',             slug: 'leh',              state: 'Ladakh',            metro: false },
  { name: 'Dharamshala',     slug: 'dharamshala',      state: 'Himachal Pradesh',  metro: false },
  { name: 'Mandi',           slug: 'mandi',            state: 'Himachal Pradesh',  metro: false },
  { name: 'Solan',           slug: 'solan',            state: 'Himachal Pradesh',  metro: false },
  { name: 'Chalthan',        slug: 'chalthan',         state: 'Gujarat',            metro: false },
  { name: 'Kakolem Beach',   slug: 'kakolem-beach',    state: 'Goa',                metro: false },
  { name: 'Yerwada',         slug: 'yerwada',          state: 'Maharashtra',         metro: false },
  { name: 'Chinchpokli',      slug: 'chinchpokli',      state: 'Maharashtra',         metro: false },
  { name: 'Palwal',            slug: 'palwal',           state: 'Haryana',             metro: false },
];

// Build a slug → city lookup for fast access
const CITY_BY_SLUG = CITIES.reduce((map, city) => {
  map[city.slug] = city;
  return map;
}, {});

module.exports = { CITIES, CITY_BY_SLUG };
