// 70+ Indian cities for escort service location pages
const CITIES = [
  // Metro Cities
  { name: 'Delhi',            slug: 'delhi',            state: 'Delhi',             metro: true,  lat: 28.6139, lon: 77.2090 },
  { name: 'Mumbai',           slug: 'mumbai',           state: 'Maharashtra',       metro: true,  lat: 19.0760, lon: 72.8777 },
  { name: 'Bangalore',        slug: 'bangalore',        state: 'Karnataka',         metro: true,  lat: 12.9716, lon: 77.5946 },
  { name: 'Hyderabad',        slug: 'hyderabad',        state: 'Telangana',         metro: true,  lat: 17.3850, lon: 78.4867 },
  { name: 'Chennai',          slug: 'chennai',          state: 'Tamil Nadu',        metro: true,  lat: 13.0827, lon: 80.2707 },
  { name: 'Kolkata',          slug: 'kolkata',          state: 'West Bengal',       metro: true,  lat: 22.5726, lon: 88.3639 },
  { name: 'Pune',             slug: 'pune',             state: 'Maharashtra',       metro: true,  lat: 18.5204, lon: 73.8567 },
  { name: 'Ahmedabad',        slug: 'ahmedabad',        state: 'Gujarat',           metro: true,  lat: 23.0225, lon: 72.5714 },
  { name: 'Noida',            slug: 'noida',            state: 'Uttar Pradesh',     metro: true,  lat: 28.5355, lon: 77.3910 },
  { name: 'Gurugram',         slug: 'gurugram',         state: 'Haryana',           metro: true,  lat: 28.4595, lon: 77.0266 },

  // Tier-1 Cities
  { name: 'Jaipur',           slug: 'jaipur',           state: 'Rajasthan',         metro: false, lat: 26.9124, lon: 75.7873 },
  { name: 'Surat',            slug: 'surat',            state: 'Gujarat',           metro: false, lat: 21.1702, lon: 72.8311 },
  { name: 'Lucknow',          slug: 'lucknow',          state: 'Uttar Pradesh',     metro: false, lat: 26.8467, lon: 80.9462 },
  { name: 'Kanpur',           slug: 'kanpur',           state: 'Uttar Pradesh',     metro: false, lat: 26.4499, lon: 80.3319 },
  { name: 'Nagpur',           slug: 'nagpur',           state: 'Maharashtra',       metro: false, lat: 21.1458, lon: 79.0882 },
  { name: 'Indore',           slug: 'indore',           state: 'Madhya Pradesh',    metro: false, lat: 22.7196, lon: 75.8577 },
  { name: 'Thane',            slug: 'thane',            state: 'Maharashtra',       metro: false, lat: 19.2183, lon: 72.9781 },
  { name: 'Bhopal',           slug: 'bhopal',           state: 'Madhya Pradesh',    metro: false, lat: 23.2599, lon: 77.4126 },
  { name: 'Visakhapatnam',    slug: 'visakhapatnam',    state: 'Andhra Pradesh',    metro: false, lat: 17.6868, lon: 83.2185 },
  { name: 'Patna',            slug: 'patna',            state: 'Bihar',             metro: false, lat: 25.5941, lon: 85.1376 },
  { name: 'Vadodara',         slug: 'vadodara',         state: 'Gujarat',           metro: false, lat: 22.3072, lon: 73.1812 },
  { name: 'Ghaziabad',        slug: 'ghaziabad',        state: 'Uttar Pradesh',     metro: false, lat: 28.6692, lon: 77.4538 },
  { name: 'Ludhiana',         slug: 'ludhiana',         state: 'Punjab',            metro: false, lat: 30.9010, lon: 75.8573 },
  { name: 'Agra',             slug: 'agra',             state: 'Uttar Pradesh',     metro: false, lat: 27.1767, lon: 78.0081 },
  { name: 'Nashik',           slug: 'nashik',           state: 'Maharashtra',       metro: false, lat: 19.9975, lon: 73.7898 },
  { name: 'Faridabad',        slug: 'faridabad',        state: 'Haryana',           metro: false, lat: 28.4089, lon: 77.3178 },
  { name: 'Meerut',           slug: 'meerut',           state: 'Uttar Pradesh',     metro: false, lat: 28.9845, lon: 77.7064 },
  { name: 'Rajkot',           slug: 'rajkot',           state: 'Gujarat',           metro: false, lat: 22.3039, lon: 70.8022 },
  { name: 'Varanasi',         slug: 'varanasi',         state: 'Uttar Pradesh',     metro: false, lat: 25.3176, lon: 82.9739 },
  { name: 'Amritsar',         slug: 'amritsar',         state: 'Punjab',            metro: false, lat: 31.6340, lon: 74.8723 },
  { name: 'Aurangabad',       slug: 'aurangabad',       state: 'Maharashtra',       metro: false, lat: 19.8762, lon: 75.3433 },
  { name: 'Ranchi',           slug: 'ranchi',           state: 'Jharkhand',         metro: false, lat: 23.3441, lon: 85.3096 },
  { name: 'Coimbatore',       slug: 'coimbatore',       state: 'Tamil Nadu',        metro: false, lat: 11.0168, lon: 76.9558 },
  { name: 'Jodhpur',          slug: 'jodhpur',          state: 'Rajasthan',         metro: false, lat: 26.2389, lon: 73.0243 },
  { name: 'Madurai',          slug: 'madurai',          state: 'Tamil Nadu',        metro: false, lat: 9.9252,  lon: 78.1198 },
  { name: 'Raipur',           slug: 'raipur',           state: 'Chhattisgarh',      metro: false, lat: 21.2514, lon: 81.6296 },
  { name: 'Kochi',            slug: 'kochi',            state: 'Kerala',            metro: false, lat: 9.9312,  lon: 76.2673 },
  { name: 'Chandigarh',       slug: 'chandigarh',       state: 'Punjab',            metro: false, lat: 30.7333, lon: 76.7794 },
  { name: 'Guwahati',         slug: 'guwahati',         state: 'Assam',             metro: false, lat: 26.1445, lon: 91.7362 },
  { name: 'Bhubaneswar',      slug: 'bhubaneswar',      state: 'Odisha',            metro: false, lat: 20.2961, lon: 85.8189 },
  { name: 'Thiruvananthapuram', slug: 'thiruvananthapuram', state: 'Kerala',        metro: false, lat: 8.5241,  lon: 76.9366 },
  { name: 'Jabalpur',         slug: 'jabalpur',         state: 'Madhya Pradesh',    metro: false, lat: 23.1815, lon: 79.9864 },
  { name: 'Gwalior',          slug: 'gwalior',          state: 'Madhya Pradesh',    metro: false, lat: 26.2183, lon: 78.1828 },
  { name: 'Vijayawada',       slug: 'vijayawada',       state: 'Andhra Pradesh',    metro: false, lat: 16.5062, lon: 80.6480 },
  { name: 'Prayagraj',        slug: 'prayagraj',        state: 'Uttar Pradesh',     metro: false, lat: 25.4358, lon: 81.8463 },
  { name: 'Bareilly',         slug: 'bareilly',         state: 'Uttar Pradesh',     metro: false, lat: 28.3670, lon: 79.4304 },
  { name: 'Aligarh',          slug: 'aligarh',          state: 'Uttar Pradesh',     metro: false, lat: 27.8974, lon: 78.0880 },
  { name: 'Moradabad',        slug: 'moradabad',        state: 'Uttar Pradesh',     metro: false, lat: 28.8389, lon: 78.7769 },
  { name: 'Gurgaon',          slug: 'gurgaon',          state: 'Haryana',           metro: false, lat: 28.4595, lon: 77.0266 },
  { name: 'Mysore',           slug: 'mysore',           state: 'Karnataka',         metro: false, lat: 12.2958, lon: 76.6394 },
  { name: 'Mangalore',        slug: 'mangalore',        state: 'Karnataka',         metro: false, lat: 12.9141, lon: 74.8560 },
  { name: 'Hubli',            slug: 'hubli',            state: 'Karnataka',         metro: false, lat: 15.3647, lon: 75.1240 },
  { name: 'Belgaum',          slug: 'belgaum',          state: 'Karnataka',         metro: false, lat: 15.8497, lon: 74.4977 },
  { name: 'Kolhapur',         slug: 'kolhapur',         state: 'Maharashtra',       metro: false, lat: 16.7050, lon: 74.2433 },
  { name: 'Solapur',          slug: 'solapur',          state: 'Maharashtra',       metro: false, lat: 17.6599, lon: 75.9064 },
  { name: 'Navi Mumbai',      slug: 'navi-mumbai',      state: 'Maharashtra',       metro: false, lat: 19.0330, lon: 73.0297 },
  { name: 'Pimpri-Chinchwad', slug: 'pimpri-chinchwad', state: 'Maharashtra',       metro: false, lat: 18.6298, lon: 73.7997 },
  { name: 'Udaipur',          slug: 'udaipur',          state: 'Rajasthan',         metro: false, lat: 24.5854, lon: 73.7125 },
  { name: 'Kota',             slug: 'kota',             state: 'Rajasthan',         metro: false, lat: 25.2138, lon: 75.8648 },
  { name: 'Ajmer',            slug: 'ajmer',            state: 'Rajasthan',         metro: false, lat: 26.4499, lon: 74.6399 },
  { name: 'Bikaner',          slug: 'bikaner',          state: 'Rajasthan',         metro: false, lat: 28.0229, lon: 73.3119 },
  { name: 'Siliguri',         slug: 'siliguri',         state: 'West Bengal',       metro: false, lat: 26.7271, lon: 88.3953 },
  { name: 'Jamshedpur',       slug: 'jamshedpur',       state: 'Jharkhand',         metro: false, lat: 22.8046, lon: 86.2029 },
  { name: 'Dhanbad',          slug: 'dhanbad',          state: 'Jharkhand',         metro: false, lat: 23.7957, lon: 86.4304 },
  { name: 'Warangal',         slug: 'warangal',         state: 'Telangana',         metro: false, lat: 17.9784, lon: 79.5941 },
  { name: 'Tirupati',         slug: 'tirupati',         state: 'Andhra Pradesh',    metro: false, lat: 13.6288, lon: 79.4192 },
  { name: 'Cuttack',          slug: 'cuttack',          state: 'Odisha',            metro: false, lat: 20.4625, lon: 85.8828 },
  { name: 'Dehradun',         slug: 'dehradun',         state: 'Uttarakhand',       metro: false, lat: 30.3165, lon: 78.0322 },
  { name: 'Shimla',           slug: 'shimla',           state: 'Himachal Pradesh',  metro: false, lat: 31.1048, lon: 77.1734 },
  { name: 'Nainital',         slug: 'nainital',         state: 'Uttarakhand',       metro: false, lat: 29.3803, lon: 79.4636 },
  { name: 'Rishikesh',        slug: 'rishikesh',        state: 'Uttarakhand',       metro: false, lat: 30.0869, lon: 78.2676 },
  { name: 'Haridwar',         slug: 'haridwar',         state: 'Uttarakhand',       metro: false, lat: 29.9457, lon: 78.1642 },
  { name: 'Mussoorie',        slug: 'mussoorie',        state: 'Uttarakhand',       metro: false, lat: 30.4598, lon: 78.0664 },
  { name: 'Goa',              slug: 'goa',              state: 'Goa',               metro: false, lat: 15.2993, lon: 74.1240 },
  { name: 'Shillong',         slug: 'shillong',         state: 'Meghalaya',         metro: false, lat: 25.5788, lon: 91.8933 },
  { name: 'Imphal',           slug: 'imphal',           state: 'Manipur',           metro: false, lat: 24.8170, lon: 93.9368 },
  { name: 'Srinagar',         slug: 'srinagar',         state: 'Jammu & Kashmir',   metro: false, lat: 34.0837, lon: 74.7973 },
  { name: 'Jammu',            slug: 'jammu',            state: 'Jammu & Kashmir',   metro: false, lat: 32.7266, lon: 74.8570 },
  { name: 'Pondicherry',      slug: 'pondicherry',      state: 'Puducherry',        metro: false, lat: 11.9416, lon: 79.8083 },

  // Additional Tier-2 & searched cities
  { name: 'Tiruchirappalli', slug: 'tiruchirappalli',  state: 'Tamil Nadu',        metro: false, lat: 10.7905, lon: 78.7047 },
  { name: 'Trichy',          slug: 'trichy',           state: 'Tamil Nadu',        metro: false, lat: 10.7905, lon: 78.7047 },
  { name: 'Salem',           slug: 'salem',            state: 'Tamil Nadu',        metro: false, lat: 11.6643, lon: 78.1460 },
  { name: 'Tirunelveli',     slug: 'tirunelveli',      state: 'Tamil Nadu',        metro: false, lat: 8.7139,  lon: 77.7567 },
  { name: 'Vellore',         slug: 'vellore',          state: 'Tamil Nadu',        metro: false, lat: 12.9165, lon: 79.1325 },
  { name: 'Erode',           slug: 'erode',            state: 'Tamil Nadu',        metro: false, lat: 11.3410, lon: 77.7172 },
  { name: 'Tiruppur',        slug: 'tiruppur',         state: 'Tamil Nadu',        metro: false, lat: 11.1085, lon: 77.3411 },
  { name: 'Thrissur',        slug: 'thrissur',         state: 'Kerala',            metro: false, lat: 10.5276, lon: 76.2144 },
  { name: 'Kozhikode',       slug: 'kozhikode',        state: 'Kerala',            metro: false, lat: 11.2588, lon: 75.7804 },
  { name: 'Kollam',          slug: 'kollam',           state: 'Kerala',            metro: false, lat: 8.8932,  lon: 76.6141 },
  { name: 'Kannur',          slug: 'kannur',           state: 'Kerala',            metro: false, lat: 11.8745, lon: 75.3704 },
  { name: 'Guntur',          slug: 'guntur',           state: 'Andhra Pradesh',    metro: false, lat: 16.3067, lon: 80.4365 },
  { name: 'Nellore',         slug: 'nellore',          state: 'Andhra Pradesh',    metro: false, lat: 14.4426, lon: 79.9865 },
  { name: 'Kurnool',         slug: 'kurnool',          state: 'Andhra Pradesh',    metro: false, lat: 15.8281, lon: 78.0373 },
  { name: 'Kakinada',        slug: 'kakinada',         state: 'Andhra Pradesh',    metro: false, lat: 16.9891, lon: 82.2475 },
  { name: 'Rajahmundry',     slug: 'rajahmundry',      state: 'Andhra Pradesh',    metro: false, lat: 17.0005, lon: 81.8040 },
  { name: 'Karimnagar',      slug: 'karimnagar',       state: 'Telangana',         metro: false, lat: 18.4386, lon: 79.1288 },
  { name: 'Nizamabad',       slug: 'nizamabad',        state: 'Telangana',         metro: false, lat: 18.6725, lon: 78.0941 },
  { name: 'Mysuru',          slug: 'mysuru',           state: 'Karnataka',         metro: false, lat: 12.2958, lon: 76.6394 },
  { name: 'Gulbarga',        slug: 'gulbarga',         state: 'Karnataka',         metro: false, lat: 17.3297, lon: 76.8343 },
  { name: 'Davangere',       slug: 'davangere',        state: 'Karnataka',         metro: false, lat: 14.4644, lon: 75.9218 },
  { name: 'Shimoga',         slug: 'shimoga',          state: 'Karnataka',         metro: false, lat: 13.9299, lon: 75.5681 },
  { name: 'Tumkur',          slug: 'tumkur',           state: 'Karnataka',         metro: false, lat: 13.3409, lon: 77.1010 },
  { name: 'Bilaspur',        slug: 'bilaspur',         state: 'Chhattisgarh',      metro: false, lat: 22.0796, lon: 82.1391 },
  { name: 'Korba',           slug: 'korba',            state: 'Chhattisgarh',      metro: false, lat: 22.3595, lon: 82.7501 },
  { name: 'Gorakhpur',       slug: 'gorakhpur',        state: 'Uttar Pradesh',     metro: false, lat: 26.7606, lon: 83.3732 },
  { name: 'Allahabad',       slug: 'allahabad',        state: 'Uttar Pradesh',     metro: false, lat: 25.4358, lon: 81.8463 },
  { name: 'Mathura',         slug: 'mathura',          state: 'Uttar Pradesh',     metro: false, lat: 27.4924, lon: 77.6737 },
  { name: 'Firozabad',       slug: 'firozabad',        state: 'Uttar Pradesh',     metro: false, lat: 27.1591, lon: 78.3957 },
  { name: 'Saharanpur',      slug: 'saharanpur',       state: 'Uttar Pradesh',     metro: false, lat: 29.9680, lon: 77.5510 },
  { name: 'Muzaffarnagar',   slug: 'muzaffarnagar',    state: 'Uttar Pradesh',     metro: false, lat: 29.4727, lon: 77.7085 },
  { name: 'Bhilai',          slug: 'bhilai',           state: 'Chhattisgarh',      metro: false, lat: 21.1938, lon: 81.3509 },
  { name: 'Durgapur',        slug: 'durgapur',         state: 'West Bengal',       metro: false, lat: 23.4793, lon: 87.3119 },
  { name: 'Asansol',         slug: 'asansol',          state: 'West Bengal',       metro: false, lat: 23.6833, lon: 86.9667 },
  { name: 'Bokaro',          slug: 'bokaro',           state: 'Jharkhand',         metro: false, lat: 23.6693, lon: 85.9913 },
  { name: 'Gaya',            slug: 'gaya',             state: 'Bihar',             metro: false, lat: 24.7914, lon: 85.0002 },
  { name: 'Muzaffarpur',     slug: 'muzaffarpur',      state: 'Bihar',             metro: false, lat: 26.1209, lon: 85.3647 },
  { name: 'Bhagalpur',       slug: 'bhagalpur',        state: 'Bihar',             metro: false, lat: 25.2540, lon: 86.9722 },

  // Tamil Nadu — remaining district HQs & towns
  { name: 'Nagapattinam',    slug: 'nagapattinam',     state: 'Tamil Nadu',        metro: false, lat: 10.7672, lon: 79.8449 },
  { name: 'Thanjavur',       slug: 'thanjavur',        state: 'Tamil Nadu',        metro: false, lat: 10.7870, lon: 79.1378 },
  { name: 'Dindigul',        slug: 'dindigul',         state: 'Tamil Nadu',        metro: false, lat: 10.3624, lon: 77.9695 },
  { name: 'Cuddalore',       slug: 'cuddalore',        state: 'Tamil Nadu',        metro: false, lat: 11.7447, lon: 79.7689 },
  { name: 'Thoothukudi',     slug: 'thoothukudi',      state: 'Tamil Nadu',        metro: false, lat: 8.7642,  lon: 78.1348 },
  { name: 'Tuticorin',       slug: 'tuticorin',        state: 'Tamil Nadu',        metro: false, lat: 8.7642,  lon: 78.1348 },
  { name: 'Nagercoil',       slug: 'nagercoil',        state: 'Tamil Nadu',        metro: false, lat: 8.1833,  lon: 77.4119 },
  { name: 'Hosur',           slug: 'hosur',            state: 'Tamil Nadu',        metro: false, lat: 12.7409, lon: 77.8253 },
  { name: 'Krishnagiri',     slug: 'krishnagiri',      state: 'Tamil Nadu',        metro: false, lat: 12.5266, lon: 78.2139 },
  { name: 'Dharmapuri',      slug: 'dharmapuri',       state: 'Tamil Nadu',        metro: false, lat: 12.1211, lon: 78.1582 },
  { name: 'Namakkal',        slug: 'namakkal',         state: 'Tamil Nadu',        metro: false, lat: 11.2196, lon: 78.1673 },
  { name: 'Sivakasi',        slug: 'sivakasi',         state: 'Tamil Nadu',        metro: false, lat: 9.4533,  lon: 77.7975 },
  { name: 'Ramanathapuram',  slug: 'ramanathapuram',   state: 'Tamil Nadu',        metro: false, lat: 9.3712,  lon: 78.8305 },
  { name: 'Virudhunagar',    slug: 'virudhunagar',     state: 'Tamil Nadu',        metro: false, lat: 9.5851,  lon: 77.9518 },
  { name: 'Sivagangai',      slug: 'sivagangai',       state: 'Tamil Nadu',        metro: false, lat: 9.8417,  lon: 78.4830 },
  { name: 'Karur',           slug: 'karur',            state: 'Tamil Nadu',        metro: false, lat: 10.9601, lon: 78.0766 },
  { name: 'Ooty',            slug: 'ooty',             state: 'Tamil Nadu',        metro: false, lat: 11.4102, lon: 76.6950 },
  { name: 'Kanchipuram',     slug: 'kanchipuram',      state: 'Tamil Nadu',        metro: false, lat: 12.8342, lon: 79.7036 },
  { name: 'Tiruvannamalai',  slug: 'tiruvannamalai',   state: 'Tamil Nadu',        metro: false, lat: 12.2253, lon: 79.0747 },
  { name: 'Villupuram',      slug: 'villupuram',       state: 'Tamil Nadu',        metro: false, lat: 11.9401, lon: 79.4927 },
  { name: 'Pudukkottai',     slug: 'pudukkottai',      state: 'Tamil Nadu',        metro: false, lat: 10.3797, lon: 78.8236 },
  { name: 'Chengalpattu',    slug: 'chengalpattu',     state: 'Tamil Nadu',        metro: false, lat: 12.6919, lon: 79.9776 },
  { name: 'Ranipet',         slug: 'ranipet',          state: 'Tamil Nadu',        metro: false, lat: 12.9220, lon: 79.3335 },
  { name: 'Tenkasi',         slug: 'tenkasi',          state: 'Tamil Nadu',        metro: false, lat: 8.9597,  lon: 77.3154 },

  // Maharashtra — remaining district HQs
  { name: 'Amravati',        slug: 'amravati',         state: 'Maharashtra',       metro: false, lat: 20.9374, lon: 77.7796 },
  { name: 'Akola',           slug: 'akola',            state: 'Maharashtra',       metro: false, lat: 20.7002, lon: 77.0082 },
  { name: 'Latur',           slug: 'latur',            state: 'Maharashtra',       metro: false, lat: 18.4088, lon: 76.5604 },
  { name: 'Nanded',          slug: 'nanded',           state: 'Maharashtra',       metro: false, lat: 19.1383, lon: 77.3210 },
  { name: 'Jalgaon',         slug: 'jalgaon',          state: 'Maharashtra',       metro: false, lat: 21.0077, lon: 75.5626 },
  { name: 'Satara',          slug: 'satara',           state: 'Maharashtra',       metro: false, lat: 17.6805, lon: 74.0183 },
  { name: 'Sangli',          slug: 'sangli',           state: 'Maharashtra',       metro: false, lat: 16.8524, lon: 74.5815 },
  { name: 'Chandrapur',      slug: 'chandrapur',       state: 'Maharashtra',       metro: false, lat: 19.9615, lon: 79.2961 },
  { name: 'Yavatmal',        slug: 'yavatmal',         state: 'Maharashtra',       metro: false, lat: 20.3888, lon: 78.1204 },

  // Rajasthan — remaining district HQs
  { name: 'Bharatpur',       slug: 'bharatpur',        state: 'Rajasthan',         metro: false, lat: 27.2152, lon: 77.4934 },
  { name: 'Alwar',           slug: 'alwar',            state: 'Rajasthan',         metro: false, lat: 27.5530, lon: 76.6346 },
  { name: 'Sikar',           slug: 'sikar',            state: 'Rajasthan',         metro: false, lat: 27.6099, lon: 75.1399 },
  { name: 'Bhilwara',        slug: 'bhilwara',         state: 'Rajasthan',         metro: false, lat: 25.3486, lon: 74.6313 },
  { name: 'Pali',            slug: 'pali',             state: 'Rajasthan',         metro: false, lat: 25.7711, lon: 73.3234 },
  { name: 'Barmer',          slug: 'barmer',           state: 'Rajasthan',         metro: false, lat: 25.7463, lon: 71.3950 },
  { name: 'Chittorgarh',     slug: 'chittorgarh',      state: 'Rajasthan',         metro: false, lat: 24.8887, lon: 74.6269 },
  { name: 'Sri Ganganagar',  slug: 'sri-ganganagar',   state: 'Rajasthan',         metro: false, lat: 29.9238, lon: 73.8772 },
  { name: 'Hanumangarh',     slug: 'hanumangarh',      state: 'Rajasthan',         metro: false, lat: 29.5803, lon: 74.3292 },

  // Gujarat — remaining cities
  { name: 'Gandhinagar',     slug: 'gandhinagar',      state: 'Gujarat',           metro: false, lat: 23.2156, lon: 72.6369 },
  { name: 'Junagadh',        slug: 'junagadh',         state: 'Gujarat',           metro: false, lat: 21.5222, lon: 70.4579 },
  { name: 'Bhavnagar',       slug: 'bhavnagar',        state: 'Gujarat',           metro: false, lat: 21.7645, lon: 72.1519 },
  { name: 'Anand',           slug: 'anand',            state: 'Gujarat',           metro: false, lat: 22.5645, lon: 72.9289 },
  { name: 'Mehsana',         slug: 'mehsana',          state: 'Gujarat',           metro: false, lat: 23.6002, lon: 72.3693 },
  { name: 'Porbandar',       slug: 'porbandar',        state: 'Gujarat',           metro: false, lat: 21.6424, lon: 69.6105 },
  { name: 'Surendranagar',   slug: 'surendranagar',    state: 'Gujarat',           metro: false, lat: 22.7280, lon: 71.6439 },

  // Punjab — remaining cities
  { name: 'Jalandhar',       slug: 'jalandhar',        state: 'Punjab',            metro: false, lat: 31.3260, lon: 75.5762 },
  { name: 'Patiala',         slug: 'patiala',          state: 'Punjab',            metro: false, lat: 30.3398, lon: 76.3869 },
  { name: 'Bathinda',        slug: 'bathinda',         state: 'Punjab',            metro: false, lat: 30.2110, lon: 74.9455 },
  { name: 'Mohali',          slug: 'mohali',           state: 'Punjab',            metro: false, lat: 30.7046, lon: 76.7179 },
  { name: 'Pathankot',       slug: 'pathankot',        state: 'Punjab',            metro: false, lat: 32.2736, lon: 75.6522 },
  { name: 'Hoshiarpur',      slug: 'hoshiarpur',       state: 'Punjab',            metro: false, lat: 31.5343, lon: 75.9117 },
  { name: 'Moga',            slug: 'moga',             state: 'Punjab',            metro: false, lat: 30.8108, lon: 75.1728 },

  // Haryana — remaining cities
  { name: 'Ambala',          slug: 'ambala',           state: 'Haryana',           metro: false, lat: 30.3782, lon: 76.7767 },
  { name: 'Hisar',           slug: 'hisar',            state: 'Haryana',           metro: false, lat: 29.1492, lon: 75.7217 },
  { name: 'Rohtak',          slug: 'rohtak',           state: 'Haryana',           metro: false, lat: 28.8955, lon: 76.6066 },
  { name: 'Panipat',         slug: 'panipat',          state: 'Haryana',           metro: false, lat: 29.3909, lon: 76.9635 },
  { name: 'Karnal',          slug: 'karnal',           state: 'Haryana',           metro: false, lat: 29.6857, lon: 76.9905 },
  { name: 'Sonipat',         slug: 'sonipat',          state: 'Haryana',           metro: false, lat: 28.9288, lon: 77.0204 },
  { name: 'Yamunanagar',     slug: 'yamunanagar',      state: 'Haryana',           metro: false, lat: 30.1290, lon: 77.2674 },
  { name: 'Bhiwani',         slug: 'bhiwani',          state: 'Haryana',           metro: false, lat: 28.7975, lon: 76.1322 },
  { name: 'Rewari',          slug: 'rewari',           state: 'Haryana',           metro: false, lat: 28.1972, lon: 76.6175 },
  { name: 'Panchkula',       slug: 'panchkula',        state: 'Haryana',           metro: false, lat: 30.6942, lon: 76.8606 },
  { name: 'Kurukshetra',     slug: 'kurukshetra',      state: 'Haryana',           metro: false, lat: 29.9695, lon: 76.8783 },

  // Madhya Pradesh — remaining cities
  { name: 'Ujjain',          slug: 'ujjain',           state: 'Madhya Pradesh',    metro: false, lat: 23.1765, lon: 75.7885 },
  { name: 'Sagar',           slug: 'sagar',            state: 'Madhya Pradesh',    metro: false, lat: 23.8388, lon: 78.7378 },
  { name: 'Satna',           slug: 'satna',            state: 'Madhya Pradesh',    metro: false, lat: 24.5728, lon: 80.8322 },
  { name: 'Rewa',            slug: 'rewa',             state: 'Madhya Pradesh',    metro: false, lat: 24.5328, lon: 81.2983 },
  { name: 'Dewas',           slug: 'dewas',            state: 'Madhya Pradesh',    metro: false, lat: 22.9676, lon: 76.0534 },
  { name: 'Chhindwara',      slug: 'chhindwara',       state: 'Madhya Pradesh',    metro: false, lat: 22.0574, lon: 78.9382 },
  { name: 'Khandwa',         slug: 'khandwa',          state: 'Madhya Pradesh',    metro: false, lat: 21.8300, lon: 76.3520 },
  { name: 'Burhanpur',       slug: 'burhanpur',        state: 'Madhya Pradesh',    metro: false, lat: 21.3123, lon: 76.2285 },

  // Uttar Pradesh — remaining cities
  { name: 'Jhansi',          slug: 'jhansi',           state: 'Uttar Pradesh',     metro: false, lat: 25.4484, lon: 78.5685 },
  { name: 'Rampur',          slug: 'rampur',           state: 'Uttar Pradesh',     metro: false, lat: 28.8089, lon: 79.0254 },
  { name: 'Bulandshahr',     slug: 'bulandshahr',      state: 'Uttar Pradesh',     metro: false, lat: 28.4071, lon: 77.8499 },
  { name: 'Etawah',          slug: 'etawah',           state: 'Uttar Pradesh',     metro: false, lat: 26.7836, lon: 79.0233 },
  { name: 'Mainpuri',        slug: 'mainpuri',         state: 'Uttar Pradesh',     metro: false, lat: 27.2290, lon: 79.0247 },
  { name: 'Rae Bareli',      slug: 'rae-bareli',       state: 'Uttar Pradesh',     metro: false, lat: 26.2229, lon: 81.2340 },
  { name: 'Unnao',           slug: 'unnao',            state: 'Uttar Pradesh',     metro: false, lat: 26.5476, lon: 80.4883 },
  { name: 'Jaunpur',         slug: 'jaunpur',          state: 'Uttar Pradesh',     metro: false, lat: 25.7462, lon: 82.6847 },
  { name: 'Azamgarh',        slug: 'azamgarh',         state: 'Uttar Pradesh',     metro: false, lat: 26.0715, lon: 83.1847 },
  { name: 'Mirzapur',        slug: 'mirzapur',         state: 'Uttar Pradesh',     metro: false, lat: 25.1449, lon: 82.5685 },
  { name: 'Sultanpur',       slug: 'sultanpur',        state: 'Uttar Pradesh',     metro: false, lat: 26.2648, lon: 82.0727 },

  // Bihar — remaining cities
  { name: 'Darbhanga',       slug: 'darbhanga',        state: 'Bihar',             metro: false, lat: 26.1542, lon: 85.8918 },
  { name: 'Purnia',          slug: 'purnia',           state: 'Bihar',             metro: false, lat: 25.7771, lon: 87.4753 },
  { name: 'Arrah',           slug: 'arrah',            state: 'Bihar',             metro: false, lat: 25.5560, lon: 84.6632 },
  { name: 'Begusarai',       slug: 'begusarai',        state: 'Bihar',             metro: false, lat: 25.4182, lon: 86.1272 },
  { name: 'Munger',          slug: 'munger',           state: 'Bihar',             metro: false, lat: 25.3742, lon: 86.4731 },
  { name: 'Hajipur',         slug: 'hajipur',          state: 'Bihar',             metro: false, lat: 25.6886, lon: 85.2097 },
  { name: 'Chapra',          slug: 'chapra',           state: 'Bihar',             metro: false, lat: 25.7771, lon: 84.7505 },
  { name: 'Sitamarhi',       slug: 'sitamarhi',        state: 'Bihar',             metro: false, lat: 26.5918, lon: 85.4891 },

  // West Bengal — remaining cities
  { name: 'Howrah',          slug: 'howrah',           state: 'West Bengal',       metro: false, lat: 22.5958, lon: 88.2636 },
  { name: 'Bardhaman',       slug: 'bardhaman',        state: 'West Bengal',       metro: false, lat: 23.2324, lon: 87.8615 },
  { name: 'Malda',           slug: 'malda',            state: 'West Bengal',       metro: false, lat: 25.0109, lon: 88.1438 },
  { name: 'Kharagpur',       slug: 'kharagpur',        state: 'West Bengal',       metro: false, lat: 22.3462, lon: 87.2320 },
  { name: 'Haldia',          slug: 'haldia',           state: 'West Bengal',       metro: false, lat: 22.0667, lon: 88.0694 },
  { name: 'Midnapore',       slug: 'midnapore',        state: 'West Bengal',       metro: false, lat: 22.4255, lon: 87.3197 },

  // Odisha — remaining cities
  { name: 'Rourkela',        slug: 'rourkela',         state: 'Odisha',            metro: false, lat: 22.2604, lon: 84.8536 },
  { name: 'Brahmapur',       slug: 'brahmapur',        state: 'Odisha',            metro: false, lat: 19.3149, lon: 84.7941 },
  { name: 'Sambalpur',       slug: 'sambalpur',        state: 'Odisha',            metro: false, lat: 21.4669, lon: 83.9756 },
  { name: 'Puri',            slug: 'puri',             state: 'Odisha',            metro: false, lat: 19.8134, lon: 85.8315 },
  { name: 'Balasore',        slug: 'balasore',         state: 'Odisha',            metro: false, lat: 21.4942, lon: 86.9340 },

  // Assam — remaining cities
  { name: 'Dibrugarh',       slug: 'dibrugarh',        state: 'Assam',             metro: false, lat: 27.4728, lon: 94.9120 },
  { name: 'Silchar',         slug: 'silchar',          state: 'Assam',             metro: false, lat: 24.8333, lon: 92.7789 },
  { name: 'Jorhat',          slug: 'jorhat',           state: 'Assam',             metro: false, lat: 26.7509, lon: 94.2037 },
  { name: 'Tezpur',          slug: 'tezpur',           state: 'Assam',             metro: false, lat: 26.6338, lon: 92.8005 },

  // Other states
  { name: 'Mangaluru',       slug: 'mangaluru',        state: 'Karnataka',         metro: false, lat: 12.9141, lon: 74.8560 },
  { name: 'Belagavi',        slug: 'belagavi',         state: 'Karnataka',         metro: false, lat: 15.8497, lon: 74.4977 },
  { name: 'Kalaburagi',      slug: 'kalaburagi',       state: 'Karnataka',         metro: false, lat: 17.3297, lon: 76.8343 },
  { name: 'Ballari',         slug: 'ballari',          state: 'Karnataka',         metro: false, lat: 15.1394, lon: 76.9214 },
  { name: 'Vijayapura',      slug: 'vijayapura',       state: 'Karnataka',         metro: false, lat: 16.8302, lon: 75.7100 },
  { name: 'Alappuzha',       slug: 'alappuzha',        state: 'Kerala',            metro: false, lat: 9.4981,  lon: 76.3388 },
  { name: 'Palakkad',        slug: 'palakkad',         state: 'Kerala',            metro: false, lat: 10.7867, lon: 76.6548 },
  { name: 'Malappuram',      slug: 'malappuram',       state: 'Kerala',            metro: false, lat: 11.0510, lon: 76.0711 },
  { name: 'Kasaragod',       slug: 'kasaragod',        state: 'Kerala',            metro: false, lat: 12.4996, lon: 74.9869 },
  { name: 'Kottayam',        slug: 'kottayam',         state: 'Kerala',            metro: false, lat: 9.5916,  lon: 76.5222 },
  { name: 'Idukki',          slug: 'idukki',           state: 'Kerala',            metro: false, lat: 9.9146,  lon: 77.1047 },
  { name: 'Agartala',        slug: 'agartala',         state: 'Tripura',           metro: false, lat: 23.8315, lon: 91.2868 },
  { name: 'Aizawl',          slug: 'aizawl',           state: 'Mizoram',           metro: false, lat: 23.7271, lon: 92.7176 },
  { name: 'Itanagar',        slug: 'itanagar',         state: 'Arunachal Pradesh', metro: false, lat: 27.0844, lon: 93.6053 },
  { name: 'Kohima',          slug: 'kohima',           state: 'Nagaland',          metro: false, lat: 25.6751, lon: 94.1077 },
  { name: 'Panaji',          slug: 'panaji',           state: 'Goa',               metro: false, lat: 15.4989, lon: 73.8278 },
  { name: 'Margao',          slug: 'margao',           state: 'Goa',               metro: false, lat: 15.2735, lon: 73.9575 },
  { name: 'Leh',             slug: 'leh',              state: 'Ladakh',            metro: false, lat: 34.1526, lon: 77.5771 },
  { name: 'Dharamshala',     slug: 'dharamshala',      state: 'Himachal Pradesh',  metro: false, lat: 32.2190, lon: 76.3234 },
  { name: 'Mandi',           slug: 'mandi',            state: 'Himachal Pradesh',  metro: false, lat: 31.7081, lon: 76.9318 },
  { name: 'Solan',           slug: 'solan',            state: 'Himachal Pradesh',  metro: false, lat: 30.9045, lon: 77.0967 },
  { name: 'Chalthan',        slug: 'chalthan',         state: 'Gujarat',            metro: false },
  { name: 'Kakolem Beach',   slug: 'kakolem-beach',    state: 'Goa',                metro: false },
  { name: 'Yerwada',         slug: 'yerwada',          state: 'Maharashtra',         metro: false },
  { name: 'Chinchpokli',      slug: 'chinchpokli',      state: 'Maharashtra',         metro: false },
  { name: 'Palwal',            slug: 'palwal',           state: 'Haryana',             metro: false },
];

// Build a slug → city lookup for fast access
const CITY_BY_SLUG = CITIES.reduce((map, city) => {
  map[city.slug] = city;
  return map;
}, {});

module.exports = { CITIES, CITY_BY_SLUG };
