// 70+ Indian cities for escort service location pages
const CITIES = [
  // Metro Cities
  { name: 'Delhi',            slug: 'delhi',            state: 'Delhi',             metro: true },
  { name: 'Mumbai',           slug: 'mumbai',           state: 'Maharashtra',       metro: true },
  { name: 'Bangalore',        slug: 'bangalore',        state: 'Karnataka',         metro: true },
  { name: 'Hyderabad',        slug: 'hyderabad',        state: 'Telangana',         metro: true },
  { name: 'Chennai',          slug: 'chennai',          state: 'Tamil Nadu',        metro: true },
  { name: 'Kolkata',          slug: 'kolkata',          state: 'West Bengal',       metro: true },
  { name: 'Pune',             slug: 'pune',             state: 'Maharashtra',       metro: true },
  { name: 'Ahmedabad',        slug: 'ahmedabad',        state: 'Gujarat',           metro: true },
  { name: 'Noida',            slug: 'noida',            state: 'Uttar Pradesh',     metro: true },
  { name: 'Gurugram',         slug: 'gurugram',         state: 'Haryana',           metro: true },

  // Tier-1 Cities
  { name: 'Jaipur',           slug: 'jaipur',           state: 'Rajasthan',         metro: false },
  { name: 'Surat',            slug: 'surat',            state: 'Gujarat',           metro: false },
  { name: 'Lucknow',          slug: 'lucknow',          state: 'Uttar Pradesh',     metro: false },
  { name: 'Kanpur',           slug: 'kanpur',           state: 'Uttar Pradesh',     metro: false },
  { name: 'Nagpur',           slug: 'nagpur',           state: 'Maharashtra',       metro: false },
  { name: 'Indore',           slug: 'indore',           state: 'Madhya Pradesh',    metro: false },
  { name: 'Thane',            slug: 'thane',            state: 'Maharashtra',       metro: false },
  { name: 'Bhopal',           slug: 'bhopal',           state: 'Madhya Pradesh',    metro: false },
  { name: 'Visakhapatnam',    slug: 'visakhapatnam',    state: 'Andhra Pradesh',    metro: false },
  { name: 'Patna',            slug: 'patna',            state: 'Bihar',             metro: false },
  { name: 'Vadodara',         slug: 'vadodara',         state: 'Gujarat',           metro: false },
  { name: 'Ghaziabad',        slug: 'ghaziabad',        state: 'Uttar Pradesh',     metro: false },
  { name: 'Ludhiana',         slug: 'ludhiana',         state: 'Punjab',            metro: false },
  { name: 'Agra',             slug: 'agra',             state: 'Uttar Pradesh',     metro: false },
  { name: 'Nashik',           slug: 'nashik',           state: 'Maharashtra',       metro: false },
  { name: 'Faridabad',        slug: 'faridabad',        state: 'Haryana',           metro: false },
  { name: 'Meerut',           slug: 'meerut',           state: 'Uttar Pradesh',     metro: false },
  { name: 'Rajkot',           slug: 'rajkot',           state: 'Gujarat',           metro: false },
  { name: 'Varanasi',         slug: 'varanasi',         state: 'Uttar Pradesh',     metro: false },
  { name: 'Amritsar',         slug: 'amritsar',         state: 'Punjab',            metro: false },
  { name: 'Aurangabad',       slug: 'aurangabad',       state: 'Maharashtra',       metro: false },
  { name: 'Ranchi',           slug: 'ranchi',           state: 'Jharkhand',         metro: false },
  { name: 'Coimbatore',       slug: 'coimbatore',       state: 'Tamil Nadu',        metro: false },
  { name: 'Jodhpur',          slug: 'jodhpur',          state: 'Rajasthan',         metro: false },
  { name: 'Madurai',          slug: 'madurai',          state: 'Tamil Nadu',        metro: false },
  { name: 'Raipur',           slug: 'raipur',           state: 'Chhattisgarh',      metro: false },
  { name: 'Kochi',            slug: 'kochi',            state: 'Kerala',            metro: false },
  { name: 'Chandigarh',       slug: 'chandigarh',       state: 'Punjab',            metro: false },
  { name: 'Guwahati',         slug: 'guwahati',         state: 'Assam',             metro: false },
  { name: 'Bhubaneswar',      slug: 'bhubaneswar',      state: 'Odisha',            metro: false },
  { name: 'Thiruvananthapuram', slug: 'thiruvananthapuram', state: 'Kerala',        metro: false },
  { name: 'Jabalpur',         slug: 'jabalpur',         state: 'Madhya Pradesh',    metro: false },
  { name: 'Gwalior',          slug: 'gwalior',          state: 'Madhya Pradesh',    metro: false },
  { name: 'Vijayawada',       slug: 'vijayawada',       state: 'Andhra Pradesh',    metro: false },
  { name: 'Prayagraj',        slug: 'prayagraj',        state: 'Uttar Pradesh',     metro: false },
  { name: 'Bareilly',         slug: 'bareilly',         state: 'Uttar Pradesh',     metro: false },
  { name: 'Aligarh',          slug: 'aligarh',          state: 'Uttar Pradesh',     metro: false },
  { name: 'Moradabad',        slug: 'moradabad',        state: 'Uttar Pradesh',     metro: false },
  { name: 'Gurgaon',          slug: 'gurgaon',          state: 'Haryana',           metro: false },
  { name: 'Mysore',           slug: 'mysore',           state: 'Karnataka',         metro: false },
  { name: 'Mangalore',        slug: 'mangalore',        state: 'Karnataka',         metro: false },
  { name: 'Hubli',            slug: 'hubli',            state: 'Karnataka',         metro: false },
  { name: 'Belgaum',          slug: 'belgaum',          state: 'Karnataka',         metro: false },
  { name: 'Kolhapur',         slug: 'kolhapur',         state: 'Maharashtra',       metro: false },
  { name: 'Solapur',          slug: 'solapur',          state: 'Maharashtra',       metro: false },
  { name: 'Navi Mumbai',      slug: 'navi-mumbai',      state: 'Maharashtra',       metro: false },
  { name: 'Pimpri-Chinchwad', slug: 'pimpri-chinchwad', state: 'Maharashtra',       metro: false },
  { name: 'Udaipur',          slug: 'udaipur',          state: 'Rajasthan',         metro: false },
  { name: 'Kota',             slug: 'kota',             state: 'Rajasthan',         metro: false },
  { name: 'Ajmer',            slug: 'ajmer',            state: 'Rajasthan',         metro: false },
  { name: 'Bikaner',          slug: 'bikaner',          state: 'Rajasthan',         metro: false },
  { name: 'Siliguri',         slug: 'siliguri',         state: 'West Bengal',       metro: false },
  { name: 'Jamshedpur',       slug: 'jamshedpur',       state: 'Jharkhand',         metro: false },
  { name: 'Dhanbad',          slug: 'dhanbad',          state: 'Jharkhand',         metro: false },
  { name: 'Warangal',         slug: 'warangal',         state: 'Telangana',         metro: false },
  { name: 'Tirupati',         slug: 'tirupati',         state: 'Andhra Pradesh',    metro: false },
  { name: 'Cuttack',          slug: 'cuttack',          state: 'Odisha',            metro: false },
  { name: 'Dehradun',         slug: 'dehradun',         state: 'Uttarakhand',       metro: false },
  { name: 'Shimla',           slug: 'shimla',           state: 'Himachal Pradesh',  metro: false },
  { name: 'Nainital',         slug: 'nainital',         state: 'Uttarakhand',       metro: false },
  { name: 'Rishikesh',        slug: 'rishikesh',        state: 'Uttarakhand',       metro: false },
  { name: 'Haridwar',         slug: 'haridwar',         state: 'Uttarakhand',       metro: false },
  { name: 'Mussoorie',        slug: 'mussoorie',        state: 'Uttarakhand',       metro: false },
  { name: 'Goa',              slug: 'goa',              state: 'Goa',               metro: false },
  { name: 'Shillong',         slug: 'shillong',         state: 'Meghalaya',         metro: false },
  { name: 'Imphal',           slug: 'imphal',           state: 'Manipur',           metro: false },
  { name: 'Srinagar',         slug: 'srinagar',         state: 'Jammu & Kashmir',   metro: false },
  { name: 'Jammu',            slug: 'jammu',            state: 'Jammu & Kashmir',   metro: false },
  { name: 'Pondicherry',      slug: 'pondicherry',      state: 'Puducherry',        metro: false },
];

// Build a slug → city lookup for fast access
const CITY_BY_SLUG = CITIES.reduce((map, city) => {
  map[city.slug] = city;
  return map;
}, {});

module.exports = { CITIES, CITY_BY_SLUG };
